package com.huatuo.clinics.cms.db.mapper;

import com.huatuo.clinics.cms.db.bean.CmsJgRoleinfo;
import com.huatuo.clinics.cms.db.bean.CmsJgRoleinfoExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface CmsJgRoleinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_roleinfo
     *
     * @mbggenerated Tue Aug 02 11:04:51 CST 2016
     */
    int countByExample(CmsJgRoleinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_roleinfo
     *
     * @mbggenerated Tue Aug 02 11:04:51 CST 2016
     */
    int deleteByExample(CmsJgRoleinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_roleinfo
     *
     * @mbggenerated Tue Aug 02 11:04:51 CST 2016
     */
    int insert(CmsJgRoleinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_roleinfo
     *
     * @mbggenerated Tue Aug 02 11:04:51 CST 2016
     */
    int insertSelective(CmsJgRoleinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_roleinfo
     *
     * @mbggenerated Tue Aug 02 11:04:51 CST 2016
     */
    List<CmsJgRoleinfo> selectByExample(CmsJgRoleinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_roleinfo
     *
     * @mbggenerated Tue Aug 02 11:04:51 CST 2016
     */
    int updateByExampleSelective(@Param("record") CmsJgRoleinfo record, @Param("example") CmsJgRoleinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_roleinfo
     *
     * @mbggenerated Tue Aug 02 11:04:51 CST 2016
     */
    int updateByExample(@Param("record") CmsJgRoleinfo record, @Param("example") CmsJgRoleinfoExample example);

	int countUserRoles(Map<String, Object> map);

	int DeleteCmsRoleinfo(Map<String, Object> map);

	void DeleteUserRoleinfo(Map<String, Object> map);

	void DeleteRoleinfomenu(Map<String, Object> map);

	CmsJgRoleinfo selectByPrimaryKey(Long roleId);

	List<String> getMenuIds(Map<String, Object> map);

	List<CmsJgRoleinfo> queryRole(Map<String, Object> map);

	int updateByPrimaryKey(CmsJgRoleinfo role);

	List<CmsJgRoleinfo> queryRoles(Map<String, Object> map);

	List<CmsJgRoleinfo> queryRoleByid(Map<String, Object> map);
}