package com.huatuo.clinics.cms.db.mapper;

import com.huatuo.clinics.cms.db.bean.CmsJgDistrict;
import com.huatuo.clinics.cms.db.bean.CmsJgDistrictExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmsJgDistrictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_district
     *
     * @mbggenerated Mon Aug 08 09:39:19 CST 2016
     */
    int countByExample(CmsJgDistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_district
     *
     * @mbggenerated Mon Aug 08 09:39:19 CST 2016
     */
    int deleteByExample(CmsJgDistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_district
     *
     * @mbggenerated Mon Aug 08 09:39:19 CST 2016
     */
    int insert(CmsJgDistrict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_district
     *
     * @mbggenerated Mon Aug 08 09:39:19 CST 2016
     */
    int insertSelective(CmsJgDistrict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_district
     *
     * @mbggenerated Mon Aug 08 09:39:19 CST 2016
     */
    List<CmsJgDistrict> selectByExample(CmsJgDistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_district
     *
     * @mbggenerated Mon Aug 08 09:39:19 CST 2016
     */
    int updateByExampleSelective(@Param("record") CmsJgDistrict record, @Param("example") CmsJgDistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_district
     *
     * @mbggenerated Mon Aug 08 09:39:19 CST 2016
     */
    int updateByExample(@Param("record") CmsJgDistrict record, @Param("example") CmsJgDistrictExample example);
}