package com.huatuo.clinics.cms.db.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.huatuo.clinics.cms.db.bean.CmsJgMenuInfoDTO;
import com.huatuo.clinics.cms.db.bean.CmsJgUserParts;
import com.huatuo.clinics.cms.db.bean.CmsJgUserinfo;
import com.huatuo.clinics.cms.db.bean.CmsJgUserinfoExample;

public interface CmsJgUserinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_userinfo
     *
     * @mbggenerated Thu Oct 20 11:28:53 CST 2016
     */
    int countByExample(CmsJgUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_userinfo
     *
     * @mbggenerated Thu Oct 20 11:28:53 CST 2016
     */
    int deleteByExample(CmsJgUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_userinfo
     *
     * @mbggenerated Thu Oct 20 11:28:53 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_userinfo
     *
     * @mbggenerated Thu Oct 20 11:28:53 CST 2016
     */
    int insert(CmsJgUserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_userinfo
     *
     * @mbggenerated Thu Oct 20 11:28:53 CST 2016
     */
    int insertSelective(CmsJgUserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_userinfo
     *
     * @mbggenerated Thu Oct 20 11:28:53 CST 2016
     */
    List<CmsJgUserinfo> selectByExample(CmsJgUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_userinfo
     *
     * @mbggenerated Thu Oct 20 11:28:53 CST 2016
     */
    CmsJgUserinfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_userinfo
     *
     * @mbggenerated Thu Oct 20 11:28:53 CST 2016
     */
    int updateByExampleSelective(@Param("record") CmsJgUserinfo record, @Param("example") CmsJgUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_userinfo
     *
     * @mbggenerated Thu Oct 20 11:28:53 CST 2016
     */
    int updateByExample(@Param("record") CmsJgUserinfo record, @Param("example") CmsJgUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_userinfo
     *
     * @mbggenerated Thu Oct 20 11:28:53 CST 2016
     */
    int updateByPrimaryKeySelective(CmsJgUserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_userinfo
     *
     * @mbggenerated Thu Oct 20 11:28:53 CST 2016
     */
    int updateByPrimaryKey(CmsJgUserinfo record);
    
     /**
     * 获取拦截
     * @param map
     * @return
     */
	List<String> getAuthority(Map<String, Object> map);
	
	/**
	 * 查询权限列表
	 * @param availableMap
	 * @return
	 */
	List<CmsJgMenuInfoDTO> selectByConditions(Map<String, Object> availableMap);

	void batchInsertRoleMenu(List<Map<String, Object>> listMaps);
	
	/**
	 * 增加权限中的权限查询
	 * @param roleId
	 * @param list
	 */
	List<CmsJgMenuInfoDTO> selectByMenus(Map<String, Object> availableMap);

	void batchDeleteRoleMenus(Map<String, Object> map);
	/**
	 * 查询重复用户名
	 * @param name
	 * @return
	 */
	CmsJgUserinfo getUser(String name);
	
	/**
	 * 查询用户信息条数
	 * @param map
	 * @return
	 */
	int countQuery(Map<String, Object> map);
	
	/**
	 * 查询所有用户信息
	 * @param map
	 * @return
	 */
	List<CmsJgUserParts> queryAllUser(Map<String, Object> map);
	
	/**
	 * 根据用户id查询用户信息
	 * @param map
	 * @return
	 */
	CmsJgUserParts getCmsUserinfo(Map<String, Object> map);
	
    
}