package com.huatuo.clinics.cms.db.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.huatuo.clinics.cms.bean.RuquestBeanDTO;
import com.huatuo.clinics.cms.db.bean.CmsJgPatrol;
import com.huatuo.clinics.cms.db.bean.CmsJgPatrolExample;

public interface CmsJgPatrolMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_patrol
     *
     * @mbggenerated Wed Feb 22 10:25:08 CST 2017
     */
    int countByExample(CmsJgPatrolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_patrol
     *
     * @mbggenerated Wed Feb 22 10:25:08 CST 2017
     */
    int deleteByExample(CmsJgPatrolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_patrol
     *
     * @mbggenerated Wed Feb 22 10:25:08 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_patrol
     *
     * @mbggenerated Wed Feb 22 10:25:08 CST 2017
     */
    int insert(CmsJgPatrol record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_patrol
     *
     * @mbggenerated Wed Feb 22 10:25:08 CST 2017
     */
    int insertSelective(CmsJgPatrol record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_patrol
     *
     * @mbggenerated Wed Feb 22 10:25:08 CST 2017
     */
    List<CmsJgPatrol> selectByExample(CmsJgPatrolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_patrol
     *
     * @mbggenerated Wed Feb 22 10:25:08 CST 2017
     */
    CmsJgPatrol selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_patrol
     *
     * @mbggenerated Wed Feb 22 10:25:08 CST 2017
     */
    int updateByExampleSelective(@Param("record") CmsJgPatrol record, @Param("example") CmsJgPatrolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_patrol
     *
     * @mbggenerated Wed Feb 22 10:25:08 CST 2017
     */
    int updateByExample(@Param("record") CmsJgPatrol record, @Param("example") CmsJgPatrolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_patrol
     *
     * @mbggenerated Wed Feb 22 10:25:08 CST 2017
     */
    int updateByPrimaryKeySelective(CmsJgPatrol record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_patrol
     *
     * @mbggenerated Wed Feb 22 10:25:08 CST 2017
     */
    int updateByPrimaryKey(CmsJgPatrol record);
    
    /**
     * 根据orgId查询机构是否已巡查
     * @param beanDTO
     * @return
     */
    int isPatrol(RuquestBeanDTO beanDTO);
    
    /**
	 * 根据机构id获取用户id
	 * @param orgId
	 * @param status
	 * @return
	 */
	String getUserIdByOrgId(@Param("orgId")String orgId,@Param("status")String status);
	
	/**
	 * 获取机构的巡查时间
	 * @param beanDTO
	 * @return
	 */
	List<Map<String, Object>> getPatrolTime(RuquestBeanDTO beanDTO);
}