package com.huatuo.clinics.cms.db.mapper;

import com.huatuo.clinics.cms.db.bean.CmsJgUserRole;
import com.huatuo.clinics.cms.db.bean.CmsJgUserRoleExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface CmsJgUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_user_role
     *
     * @mbggenerated Tue Aug 02 11:04:25 CST 2016
     */
    int countByExample(CmsJgUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_user_role
     *
     * @mbggenerated Tue Aug 02 11:04:25 CST 2016
     */
    int deleteByExample(CmsJgUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_user_role
     *
     * @mbggenerated Tue Aug 02 11:04:25 CST 2016
     */
    int insert(CmsJgUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_user_role
     *
     * @mbggenerated Tue Aug 02 11:04:25 CST 2016
     */
    int insertSelective(CmsJgUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_user_role
     *
     * @mbggenerated Tue Aug 02 11:04:25 CST 2016
     */
    List<CmsJgUserRole> selectByExample(CmsJgUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_user_role
     *
     * @mbggenerated Tue Aug 02 11:04:25 CST 2016
     */
    int updateByExampleSelective(@Param("record") CmsJgUserRole record, @Param("example") CmsJgUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_user_role
     *
     * @mbggenerated Tue Aug 02 11:04:25 CST 2016
     */
    int updateByExample(@Param("record") CmsJgUserRole record, @Param("example") CmsJgUserRoleExample example);
    
    /**
     * 用户关联角色
     * @param userId
     * @param roleId
     */
	int insertUserAndRole(Map<String,Object> map);
}