package com.huatuo.clinics.cms.db.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.huatuo.clinics.cms.db.bean.CmsJgOrg;
import com.huatuo.clinics.cms.db.bean.CmsJgOrgExample;

public interface CmsJgOrgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_org
     *
     * @mbggenerated Thu Nov 17 10:08:48 CST 2016
     */
    int countByExample(CmsJgOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_org
     *
     * @mbggenerated Thu Nov 17 10:08:48 CST 2016
     */
    int deleteByExample(CmsJgOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_org
     *
     * @mbggenerated Thu Nov 17 10:08:48 CST 2016
     */
    int insert(CmsJgOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_org
     *
     * @mbggenerated Thu Nov 17 10:08:48 CST 2016
     */
    int insertSelective(CmsJgOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_org
     *
     * @mbggenerated Thu Nov 17 10:08:48 CST 2016
     */
    List<CmsJgOrg> selectByExample(CmsJgOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_org
     *
     * @mbggenerated Thu Nov 17 10:08:48 CST 2016
     */
    int updateByExampleSelective(@Param("record") CmsJgOrg record, @Param("example") CmsJgOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_org
     *
     * @mbggenerated Thu Nov 17 10:08:48 CST 2016
     */
    int updateByExample(@Param("record") CmsJgOrg record, @Param("example") CmsJgOrgExample example);
     /**
     * 查询机构信息条数
     * @param map
     * @return
     */
	int countOrg(Map<String, Object> map);
	
	  /**
     * 分页查询机构信息
     * @param map
     * @return
     */
	List<CmsJgOrg> queryOrgPage(Map<String, Object> map);
	
	/**
	 * 通过id查询机构信息
	 * @param map
	 * @return
	 */
	CmsJgOrg queryOrgById(Map<String, Object> map);
}