package com.huatuo.clinics.cms.db.mapper;

import com.huatuo.clinics.cms.db.bean.CmsJgOrdercheck;
import com.huatuo.clinics.cms.db.bean.CmsJgOrdercheckExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmsJgOrdercheckMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_ordercheck
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    int countByExample(CmsJgOrdercheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_ordercheck
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    int deleteByExample(CmsJgOrdercheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_ordercheck
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    int deleteByPrimaryKey(String checkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_ordercheck
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    int insert(CmsJgOrdercheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_ordercheck
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    int insertSelective(CmsJgOrdercheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_ordercheck
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    List<CmsJgOrdercheck> selectByExample(CmsJgOrdercheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_ordercheck
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    CmsJgOrdercheck selectByPrimaryKey(String checkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_ordercheck
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    int updateByExampleSelective(@Param("record") CmsJgOrdercheck record, @Param("example") CmsJgOrdercheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_ordercheck
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    int updateByExample(@Param("record") CmsJgOrdercheck record, @Param("example") CmsJgOrdercheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_ordercheck
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    int updateByPrimaryKeySelective(CmsJgOrdercheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_ordercheck
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    int updateByPrimaryKey(CmsJgOrdercheck record);
}