package com.huatuo.clinics.cms.db.mapper;

import com.huatuo.clinics.cms.db.bean.CmsJgUserextend;
import com.huatuo.clinics.cms.db.bean.CmsJgUserextendExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmsJgUserextendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_userextend
     *
     * @mbggenerated Mon Aug 08 11:21:58 CST 2016
     */
    int countByExample(CmsJgUserextendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_userextend
     *
     * @mbggenerated Mon Aug 08 11:21:58 CST 2016
     */
    int deleteByExample(CmsJgUserextendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_userextend
     *
     * @mbggenerated Mon Aug 08 11:21:58 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_userextend
     *
     * @mbggenerated Mon Aug 08 11:21:58 CST 2016
     */
    int insert(CmsJgUserextend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_userextend
     *
     * @mbggenerated Mon Aug 08 11:21:58 CST 2016
     */
    int insertSelective(CmsJgUserextend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_userextend
     *
     * @mbggenerated Mon Aug 08 11:21:58 CST 2016
     */
    List<CmsJgUserextend> selectByExample(CmsJgUserextendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_userextend
     *
     * @mbggenerated Mon Aug 08 11:21:58 CST 2016
     */
    CmsJgUserextend selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_userextend
     *
     * @mbggenerated Mon Aug 08 11:21:58 CST 2016
     */
    int updateByExampleSelective(@Param("record") CmsJgUserextend record, @Param("example") CmsJgUserextendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_userextend
     *
     * @mbggenerated Mon Aug 08 11:21:58 CST 2016
     */
    int updateByExample(@Param("record") CmsJgUserextend record, @Param("example") CmsJgUserextendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_userextend
     *
     * @mbggenerated Mon Aug 08 11:21:58 CST 2016
     */
    int updateByPrimaryKeySelective(CmsJgUserextend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_userextend
     *
     * @mbggenerated Mon Aug 08 11:21:58 CST 2016
     */
    int updateByPrimaryKey(CmsJgUserextend record);
}