package com.huatuo.clinics.cms.db.mapper;

import com.huatuo.clinics.cms.db.bean.CmsJgAddress;
import com.huatuo.clinics.cms.db.bean.CmsJgAddressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmsJgAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_address
     *
     * @mbggenerated Mon Aug 08 09:39:39 CST 2016
     */
    int countByExample(CmsJgAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_address
     *
     * @mbggenerated Mon Aug 08 09:39:39 CST 2016
     */
    int deleteByExample(CmsJgAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_address
     *
     * @mbggenerated Mon Aug 08 09:39:39 CST 2016
     */
    Integer insert(CmsJgAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_address
     *
     * @mbggenerated Mon Aug 08 09:39:39 CST 2016
     */
    int insertSelective(CmsJgAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_address
     *
     * @mbggenerated Mon Aug 08 09:39:39 CST 2016
     */
    List<CmsJgAddress> selectByExample(CmsJgAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_address
     *
     * @mbggenerated Mon Aug 08 09:39:39 CST 2016
     */
    int updateByExampleSelective(@Param("record") CmsJgAddress record, @Param("example") CmsJgAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_address
     *
     * @mbggenerated Mon Aug 08 09:39:39 CST 2016
     */
    int updateByExample(@Param("record") CmsJgAddress record, @Param("example") CmsJgAddressExample example);
}