package com.huatuo.clinics.cms.db.mapper;

import com.huatuo.clinics.cms.db.bean.CmsJgOrdercheckDtl;
import com.huatuo.clinics.cms.db.bean.CmsJgOrdercheckDtlExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmsJgOrdercheckDtlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_ordercheck_dtl
     *
     * @mbggenerated Sun Oct 09 11:18:36 CST 2016
     */
    int countByExample(CmsJgOrdercheckDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_ordercheck_dtl
     *
     * @mbggenerated Sun Oct 09 11:18:36 CST 2016
     */
    int deleteByExample(CmsJgOrdercheckDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_ordercheck_dtl
     *
     * @mbggenerated Sun Oct 09 11:18:36 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_ordercheck_dtl
     *
     * @mbggenerated Sun Oct 09 11:18:36 CST 2016
     */
    int insert(CmsJgOrdercheckDtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_ordercheck_dtl
     *
     * @mbggenerated Sun Oct 09 11:18:36 CST 2016
     */
    int insertSelective(CmsJgOrdercheckDtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_ordercheck_dtl
     *
     * @mbggenerated Sun Oct 09 11:18:36 CST 2016
     */
    List<CmsJgOrdercheckDtl> selectByExample(CmsJgOrdercheckDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_ordercheck_dtl
     *
     * @mbggenerated Sun Oct 09 11:18:36 CST 2016
     */
    CmsJgOrdercheckDtl selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_ordercheck_dtl
     *
     * @mbggenerated Sun Oct 09 11:18:36 CST 2016
     */
    int updateByExampleSelective(@Param("record") CmsJgOrdercheckDtl record, @Param("example") CmsJgOrdercheckDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_ordercheck_dtl
     *
     * @mbggenerated Sun Oct 09 11:18:36 CST 2016
     */
    int updateByExample(@Param("record") CmsJgOrdercheckDtl record, @Param("example") CmsJgOrdercheckDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_ordercheck_dtl
     *
     * @mbggenerated Sun Oct 09 11:18:36 CST 2016
     */
    int updateByPrimaryKeySelective(CmsJgOrdercheckDtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_ordercheck_dtl
     *
     * @mbggenerated Sun Oct 09 11:18:36 CST 2016
     */
    int updateByPrimaryKey(CmsJgOrdercheckDtl record);
}