package com.huatuo.clinics.cms.db.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.huatuo.clinics.cms.db.bean.CmsJgMenuInfoDTO;
import com.huatuo.clinics.cms.db.bean.CmsJgMenuinfo;
import com.huatuo.clinics.cms.db.bean.CmsJgMenuinfoExample;

public interface CmsJgMenuinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_menuinfo
     *
     * @mbggenerated Thu Nov 10 11:37:42 CST 2016
     */
    int countByExample(CmsJgMenuinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_menuinfo
     *
     * @mbggenerated Thu Nov 10 11:37:42 CST 2016
     */
    int deleteByExample(CmsJgMenuinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_menuinfo
     *
     * @mbggenerated Thu Nov 10 11:37:42 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_menuinfo
     *
     * @mbggenerated Thu Nov 10 11:37:42 CST 2016
     */
    int insert(CmsJgMenuinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_menuinfo
     *
     * @mbggenerated Thu Nov 10 11:37:42 CST 2016
     */
    int insertSelective(CmsJgMenuinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_menuinfo
     *
     * @mbggenerated Thu Nov 10 11:37:42 CST 2016
     */
    List<CmsJgMenuinfo> selectByExample(CmsJgMenuinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_menuinfo
     *
     * @mbggenerated Thu Nov 10 11:37:42 CST 2016
     */
    CmsJgMenuinfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_menuinfo
     *
     * @mbggenerated Thu Nov 10 11:37:42 CST 2016
     */
    int updateByExampleSelective(@Param("record") CmsJgMenuinfo record, @Param("example") CmsJgMenuinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_menuinfo
     *
     * @mbggenerated Thu Nov 10 11:37:42 CST 2016
     */
    int updateByExample(@Param("record") CmsJgMenuinfo record, @Param("example") CmsJgMenuinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_menuinfo
     *
     * @mbggenerated Thu Nov 10 11:37:42 CST 2016
     */
    int updateByPrimaryKeySelective(CmsJgMenuinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_jg_menuinfo
     *
     * @mbggenerated Thu Nov 10 11:37:42 CST 2016
     */
    int updateByPrimaryKey(CmsJgMenuinfo record);
    
    List<CmsJgMenuInfoDTO> selectCmsMenuInfos();
}