package com.huatuo.clinics.cms.db.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.huatuo.clinics.cms.db.bean.CsOutpOrderDtl;
import com.huatuo.clinics.cms.db.bean.CsOutpOrderDtlExample;

public interface CsOutpOrderDtlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_outp_order_dtl
     *
     * @mbggenerated Wed Aug 17 16:01:43 CST 2016
     */
    int countByExample(CsOutpOrderDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_outp_order_dtl
     *
     * @mbggenerated Wed Aug 17 16:01:43 CST 2016
     */
    int deleteByExample(CsOutpOrderDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_outp_order_dtl
     *
     * @mbggenerated Wed Aug 17 16:01:43 CST 2016
     */
    int insert(CsOutpOrderDtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_outp_order_dtl
     *
     * @mbggenerated Wed Aug 17 16:01:43 CST 2016
     */
    int insertSelective(CsOutpOrderDtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_outp_order_dtl
     *
     * @mbggenerated Wed Aug 17 16:01:43 CST 2016
     */
    List<CsOutpOrderDtl> selectByExample(CsOutpOrderDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_outp_order_dtl
     *
     * @mbggenerated Wed Aug 17 16:01:43 CST 2016
     */
    int updateByExampleSelective(@Param("record") CsOutpOrderDtl record, @Param("example") CsOutpOrderDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_outp_order_dtl
     *
     * @mbggenerated Wed Aug 17 16:01:43 CST 2016
     */
    int updateByExample(@Param("record") CsOutpOrderDtl record, @Param("example") CsOutpOrderDtlExample example);
    
    /**
   	 * 通过主键拿到处方详情
   	 * @param ordDtlId
   	 * @return
   	 */
   	CsOutpOrderDtl getDelById(String ordDtlId);
   	
   	/**
   	 * 批量新增处方详情
   	 * @param list
   	 * @return
   	 */
   	int addOrderDtl(List<CsOutpOrderDtl> list);
   	
   	/**
   	 * 修改处方详情
   	 * @param orderDtl
   	 * @return
   	 */
   	int update(CsOutpOrderDtl orderDtl);
   	
   	/**
	 * 统计未收费处方详情
	 * @return
	 */
   	int countOrderDtl(String ordId);
   	/**
   	 * 更新退回数量
   	 * @param dtl2
   	 * @return
   	 */
	int updateSelect(CsOutpOrderDtl dtl2);
	
	List<CsOutpOrderDtl> selectByExampleWithBLOBs(CsOutpOrderDtlExample example);
}