package com.huatuo.clinics.cms.db.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.huatuo.clinics.cms.db.bean.OmDicClinicalItemMapExample;
import com.huatuo.clinics.cms.db.bean.OmDicClinicalItemMapKey;

public interface OmDicClinicalItemMapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table om_dic_clinical_item_map
     *
     * @mbggenerated Fri Mar 11 10:21:05 CST 2016
     */
    int countByExample(OmDicClinicalItemMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table om_dic_clinical_item_map
     *
     * @mbggenerated Fri Mar 11 10:21:05 CST 2016
     */
    int deleteByExample(OmDicClinicalItemMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table om_dic_clinical_item_map
     *
     * @mbggenerated Fri Mar 11 10:21:05 CST 2016
     */
    int deleteByPrimaryKey(OmDicClinicalItemMapKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table om_dic_clinical_item_map
     *
     * @mbggenerated Fri Mar 11 10:21:05 CST 2016
     */
    int insert(OmDicClinicalItemMapKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table om_dic_clinical_item_map
     *
     * @mbggenerated Fri Mar 11 10:21:05 CST 2016
     */
    int insertSelective(OmDicClinicalItemMapKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table om_dic_clinical_item_map
     *
     * @mbggenerated Fri Mar 11 10:21:05 CST 2016
     */
    List<OmDicClinicalItemMapKey> selectByExample(OmDicClinicalItemMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table om_dic_clinical_item_map
     *
     * @mbggenerated Fri Mar 11 10:21:05 CST 2016
     */
    int updateByExampleSelective(@Param("record") OmDicClinicalItemMapKey record, @Param("example") OmDicClinicalItemMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table om_dic_clinical_item_map
     *
     * @mbggenerated Fri Mar 11 10:21:05 CST 2016
     */
    int updateByExample(@Param("record") OmDicClinicalItemMapKey record, @Param("example") OmDicClinicalItemMapExample example);

	int updateByPrimaryKey(OmDicClinicalItemMapKey omDicClinicalItemMapKey);

	int delete(String clinicalId) throws Exception;

	String getChargeIdByClinicalId(String clinicalItemId);
}