package com.huatuo.clinics.cms.db.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.huatuo.clinics.cms.db.bean.OpmDicDepartment;
import com.huatuo.clinics.cms.db.bean.OpmDicDepartmentExample;

public interface OpmDicDepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opm_dic_department
     *
     * @mbggenerated Tue Mar 22 10:49:51 CST 2016
     */
    int countByExample(OpmDicDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opm_dic_department
     *
     * @mbggenerated Tue Mar 22 10:49:51 CST 2016
     */
    int deleteByExample(OpmDicDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opm_dic_department
     *
     * @mbggenerated Tue Mar 22 10:49:51 CST 2016
     */
    int deleteByPrimaryKey(String depId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opm_dic_department
     *
     * @mbggenerated Tue Mar 22 10:49:51 CST 2016
     */
    int insert(OpmDicDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opm_dic_department
     *
     * @mbggenerated Tue Mar 22 10:49:51 CST 2016
     */
    int insertSelective(OpmDicDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opm_dic_department
     *
     * @mbggenerated Tue Mar 22 10:49:51 CST 2016
     */
    List<OpmDicDepartment> selectByExample(OpmDicDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opm_dic_department
     *
     * @mbggenerated Tue Mar 22 10:49:51 CST 2016
     */
    OpmDicDepartment selectByPrimaryKey(String depId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opm_dic_department
     *
     * @mbggenerated Tue Mar 22 10:49:51 CST 2016
     */
    int updateByExampleSelective(@Param("record") OpmDicDepartment record, @Param("example") OpmDicDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opm_dic_department
     *
     * @mbggenerated Tue Mar 22 10:49:51 CST 2016
     */
    int updateByExample(@Param("record") OpmDicDepartment record, @Param("example") OpmDicDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opm_dic_department
     *
     * @mbggenerated Tue Mar 22 10:49:51 CST 2016
     */
    int updateByPrimaryKeySelective(OpmDicDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opm_dic_department
     *
     * @mbggenerated Tue Mar 22 10:49:51 CST 2016
     */
    int updateByPrimaryKey(OpmDicDepartment record);
    
    /**
     * 根据orgId查询科室
     * @param map
     * @return
     */
	List<OpmDicDepartment> queryDepId(Map<String, Object> map);
}