package com.huatuo.clinics.cms.db.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.huatuo.clinics.cms.db.bean.RsEmpiPatientAllergicDrug;
import com.huatuo.clinics.cms.db.bean.RsEmpiPatientAllergicDrugExample;

public interface RsEmpiPatientAllergicDrugMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_empi_patient_allergic_drug
     *
     * @mbggenerated Fri Mar 11 10:21:05 CST 2016
     */
    int countByExample(RsEmpiPatientAllergicDrugExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_empi_patient_allergic_drug
     *
     * @mbggenerated Fri Mar 11 10:21:05 CST 2016
     */
    int deleteByExample(RsEmpiPatientAllergicDrugExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_empi_patient_allergic_drug
     *
     * @mbggenerated Fri Mar 11 10:21:05 CST 2016
     */
    int insert(RsEmpiPatientAllergicDrug record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_empi_patient_allergic_drug
     *
     * @mbggenerated Fri Mar 11 10:21:05 CST 2016
     */
    int insertSelective(RsEmpiPatientAllergicDrug record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_empi_patient_allergic_drug
     *
     * @mbggenerated Fri Mar 11 10:21:05 CST 2016
     */
    List<RsEmpiPatientAllergicDrug> selectByExample(RsEmpiPatientAllergicDrugExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_empi_patient_allergic_drug
     *
     * @mbggenerated Fri Mar 11 10:21:05 CST 2016
     */
    int updateByExampleSelective(@Param("record") RsEmpiPatientAllergicDrug record, @Param("example") RsEmpiPatientAllergicDrugExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_empi_patient_allergic_drug
     *
     * @mbggenerated Fri Mar 11 10:21:05 CST 2016
     */
    int updateByExample(@Param("record") RsEmpiPatientAllergicDrug record, @Param("example") RsEmpiPatientAllergicDrugExample example);
}