package com.huatuo.clinics.cms.db.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.huatuo.clinics.cms.db.bean.RsEmpiPatientInfo;
import com.huatuo.clinics.cms.db.bean.RsEmpiPatientInfoExample;

public interface RsEmpiPatientInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_empi_patient_info
     *
     * @mbggenerated Wed Mar 23 18:47:36 CST 2016
     */
    int countByExample(RsEmpiPatientInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_empi_patient_info
     *
     * @mbggenerated Wed Mar 23 18:47:36 CST 2016
     */
    int deleteByExample(RsEmpiPatientInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_empi_patient_info
     *
     * @mbggenerated Wed Mar 23 18:47:36 CST 2016
     */
    int deleteByPrimaryKey(String patientId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_empi_patient_info
     *
     * @mbggenerated Wed Mar 23 18:47:36 CST 2016
     */
    int insert(RsEmpiPatientInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_empi_patient_info
     *
     * @mbggenerated Wed Mar 23 18:47:36 CST 2016
     */
    int insertSelective(RsEmpiPatientInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_empi_patient_info
     *
     * @mbggenerated Wed Mar 23 18:47:36 CST 2016
     */
    List<RsEmpiPatientInfo> selectByExample(RsEmpiPatientInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_empi_patient_info
     *
     * @mbggenerated Wed Mar 23 18:47:36 CST 2016
     */
    RsEmpiPatientInfo selectByPrimaryKey(String patientId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_empi_patient_info
     *
     * @mbggenerated Wed Mar 23 18:47:36 CST 2016
     */
    int updateByExampleSelective(@Param("record") RsEmpiPatientInfo record, @Param("example") RsEmpiPatientInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_empi_patient_info
     *
     * @mbggenerated Wed Mar 23 18:47:36 CST 2016
     */
    int updateByExample(@Param("record") RsEmpiPatientInfo record, @Param("example") RsEmpiPatientInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_empi_patient_info
     *
     * @mbggenerated Wed Mar 23 18:47:36 CST 2016
     */
    int updateByPrimaryKeySelective(RsEmpiPatientInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_empi_patient_info
     *
     * @mbggenerated Wed Mar 23 18:47:36 CST 2016
     */
    int updateByPrimaryKey(RsEmpiPatientInfo record);
    
    /**
  	 * 通过数据库中身份证id来获得对应的主键id
  	 * @param cardId
  	 * @return
  	 */
  	String getIdByTeleNum(Map<Object, String> map);
}