package com.huatuo.clinics.cms.db.mapper;

import com.huatuo.clinics.cms.db.bean.SmCliAreaCoverDtl;
import com.huatuo.clinics.cms.db.bean.SmCliAreaCoverDtlExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmCliAreaCoverDtlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_cover_dtl
     *
     * @mbggenerated Thu Aug 11 17:36:41 CST 2016
     */
    int countByExample(SmCliAreaCoverDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_cover_dtl
     *
     * @mbggenerated Thu Aug 11 17:36:41 CST 2016
     */
    int deleteByExample(SmCliAreaCoverDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_cover_dtl
     *
     * @mbggenerated Thu Aug 11 17:36:41 CST 2016
     */
    int deleteByPrimaryKey(String areaCoverDtlId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_cover_dtl
     *
     * @mbggenerated Thu Aug 11 17:36:41 CST 2016
     */
    int insert(SmCliAreaCoverDtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_cover_dtl
     *
     * @mbggenerated Thu Aug 11 17:36:41 CST 2016
     */
    int insertSelective(SmCliAreaCoverDtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_cover_dtl
     *
     * @mbggenerated Thu Aug 11 17:36:41 CST 2016
     */
    List<SmCliAreaCoverDtl> selectByExample(SmCliAreaCoverDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_cover_dtl
     *
     * @mbggenerated Thu Aug 11 17:36:41 CST 2016
     */
    SmCliAreaCoverDtl selectByPrimaryKey(String areaCoverDtlId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_cover_dtl
     *
     * @mbggenerated Thu Aug 11 17:36:41 CST 2016
     */
    int updateByExampleSelective(@Param("record") SmCliAreaCoverDtl record, @Param("example") SmCliAreaCoverDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_cover_dtl
     *
     * @mbggenerated Thu Aug 11 17:36:41 CST 2016
     */
    int updateByExample(@Param("record") SmCliAreaCoverDtl record, @Param("example") SmCliAreaCoverDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_cover_dtl
     *
     * @mbggenerated Thu Aug 11 17:36:41 CST 2016
     */
    int updateByPrimaryKeySelective(SmCliAreaCoverDtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_cover_dtl
     *
     * @mbggenerated Thu Aug 11 17:36:41 CST 2016
     */
    int updateByPrimaryKey(SmCliAreaCoverDtl record);
}