package com.huatuo.clinics.cms.db.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.huatuo.clinics.cms.bean.RuquestBeanDTO;
import com.huatuo.clinics.cms.bean.mrcDTO;
import com.huatuo.clinics.cms.bean.ReportResult2DTO;
import com.huatuo.clinics.cms.bean.ReportResultDTO;
import com.huatuo.clinics.cms.db.bean.SmCliAreaCover;
import com.huatuo.clinics.cms.db.bean.SmCliAreaCoverExample;
import com.huatuo.clinics.cms.db.bean.ReportResultDB;

public interface SmCliAreaCoverMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_cover
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    int countByExample(SmCliAreaCoverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_cover
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    int deleteByExample(SmCliAreaCoverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_cover
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    int deleteByPrimaryKey(String areaCoverId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_cover
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    int insert(SmCliAreaCover record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_cover
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    int insertSelective(SmCliAreaCover record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_cover
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    List<SmCliAreaCover> selectByExample(SmCliAreaCoverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_cover
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    SmCliAreaCover selectByPrimaryKey(String areaCoverId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_cover
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    int updateByExampleSelective(@Param("record") SmCliAreaCover record, @Param("example") SmCliAreaCoverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_cover
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    int updateByExample(@Param("record") SmCliAreaCover record, @Param("example") SmCliAreaCoverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_cover
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    int updateByPrimaryKeySelective(SmCliAreaCover record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_cover
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    int updateByPrimaryKey(SmCliAreaCover record);
    
    /**
     * 查询截止当前时间区域下的各个镇的诊所数量
     * @param map 
     * @return
     */
	List<ReportResultDB> queryNameAndQty(Map<String, Object> map);
	
	/**
	 * 查询截止当前时间区域下前十的病种
	 * @param map
	 * @return
	 */
	List<ReportResultDB> queryIncidence(Map<String, Object> map);
	
	/**
	 * 查询截止当前时间区域下诊所评级情况
	 * @param map
	 * @return
	 */
	List<ReportResultDB> queryGrade(Map<String, Object> map);

	List<SmCliAreaCover> select(RuquestBeanDTO ruquestBeanDTO);

	List<ReportResultDTO> queryType(RuquestBeanDTO ruquestBeanDTO);
	
	/**
	 * 查询截止当前时间区域下各个镇的门诊总量
	 * @param map
	 * @return
	 */
	List<ReportResultDB> queryOperate(Map<String, Object> map);
	
	/**
	 * 个体诊所运营情况概览
	 * @param map
	 * @return
	 */
//	List<reportResultDB> queryOperateOutline(Map<String, Object> map);
	
	/**
	 * 个体诊所初复诊门诊量统计(包含同比和环比)
	 * @param map
	 * @return
	 */
	List<ReportResultDB> queryVisit(Map<String, Object> map);
	
	/**
	 * 服务总量下级区域概括
	 * @param map
	 * @return
	 */
	List<ReportResultDB> querySubordinate(Map<String, Object> map);
	
	/**
	 *  平均门诊量概括
	 * @param map
	 * @return
	 */
	List<ReportResultDB> queryAveOutpatient(Map<String, Object> map);
	
	/**
	 * 服务总量时间趋势
	 * @param map
	 * @return
	 */
	List<ReportResultDB> queryTimeTrend(Map<String, Object> map);
	
	/**
	 * 查询门诊总量
	 * @param map
	 * @return
	 */
	List<ReportResultDB> querySum(Map<String, Object> map);
	
	/**
	 * 查询初诊
	 * @param map
	 * @return
	 */
	List<ReportResultDB> queryFirstVisit(Map<String, Object> map);
	
	/**
	 * 查询复诊
	 * @param map
	 * @return
	 */
	List<ReportResultDB> queryRepeatVisit(Map<String, Object> map);
	
	/**
	 * 查询西医门诊
	 * @param map
	 * @return
	 */
	List<ReportResultDB> queryWestVisit(Map<String, Object> map);
	
	/**
	 * 查询中医门诊
	 * @param map
	 * @return
	 */
	List<ReportResultDB> queryInVisit(Map<String, Object> map);
	
	/**
	 * 查询诊所数量
	 * @param map
	 * @return
	 */
	List<ReportResultDB> queryClQty(Map<String, Object> map);
	/**
	 * 诊所资源信息总表
	 * @param ruquestBeanDTO
	 * @return
	 */
	List<Map<String, String>> Information(RuquestBeanDTO ruquestBeanDTO);
	/**
	 * 诊所资源行政区划
	 * @param ruquestBeanDTO
	 * @return
	 */
	List<ReportResultDTO> administrativeJson(RuquestBeanDTO ruquestBeanDTO);
	
	/**
	 * 查询当月服务人次
	 * @param map
	 * @return
	 */
	List<ReportResultDB> queryServiceQty(Map<String, Object> map);
	
	/**
	 * 查询不同类型诊所日人均服务人次分布
	 * @param map
	 * @return
	 */
	List<ReportResultDB> queryServiceEff(Map<String, Object> map);
	
	/**
	 * 下级区域概括
	 * @param map
	 * @return
	 */
	List<ReportResultDB> queryJunior(Map<String, Object> map);
	/**
	 * 诊所基本信息-时间趋势
	 */
	ReportResult2DTO timeseries(RuquestBeanDTO ruquestBeanDTO);
	/**
	 * 辖区总体概况-个体诊所人员岗位分布
	 */
	mrcDTO areaPopulationStation(RuquestBeanDTO ruquestBeanDTO);

	List<ReportResultDTO> areaDoctorTitle(RuquestBeanDTO ruquestBeanDTO);

	List<Map<String, Object>> PositionDistribution(RuquestBeanDTO ruquestBeanDTO);

	List<Map<String, String>> DoctorTitle(RuquestBeanDTO ruquestBeanDTO);
	/**
	 * 查询累计
	 * @param ruquestBeanDTO
	 * @return
	 */
	List<SmCliAreaCover> selectTotal(RuquestBeanDTO ruquestBeanDTO);

	List<ReportResultDTO> queryTypeTotal(RuquestBeanDTO ruquestBeanDTO);
	
	/**
	 * 查询当年人均就诊费用
	 * @param map
	 * @return
	 */
	List<ReportResultDB> queryCostQty(Map<String, Object> map);
	
	/**
	 * 各类型个体诊所人均就诊费用概况分析
	 * @param map
	 * @return
	 */
	List<ReportResultDB> queryCostType(Map<String, Object> map);
	
	/**
	 * 资质监管许可证到期数量查询
	 * @param map
	 * @return
	 */
	String queryQuality(Map<String, Object> map);
	/**
	 * 医疗服务能力分布概况-人员数量的平均分布
	 */
	List<Map<String, String>> headcountAvg(RuquestBeanDTO ruquestBeanDTO);
	/**
	 * 医疗服务能力分布概况-医生职称的平均分布
	 */
	List<Map<String, String>> doctorAbility(RuquestBeanDTO ruquestBeanDTO);
	/**
	 * 医疗服务能力分布概况-个体诊所人员构成信息总表
	 */
	List<Map<String, String>> PersonnelForm(RuquestBeanDTO ruquestBeanDTO);
	/**
	 * 查询排名前十病种
	 * @param map
	 * @return
	 */
	List<ReportResultDB> queryReIncidence(Map<String, Object> map);
	
	/**
	 * 特定病种分析
	 * @param map
	 * @return
	 */
	List<ReportResultDB> queryReGiven(Map<String, Object> map);
	
	/**
	 * 查询所有病种的总数量
	 * @param map
	 * @return
	 */
	String queryReIncidenceSum(Map<String, Object> map);
	
	/**
	 * 查询所有病种的总数量
	 * @param map
	 * @return
	 */
	String queryIncidenceSum(Map<String, Object> map);
	
	/**
	 * 查询所有病种的总数量(年季月)
	 * @param map
	 * @return
	 */
	String queryDiseasesSum(Map<String, Object> map);
	
	/**
	 * 查询排名前十病种(年季月)
	 * @param map
	 * @return
	 */
	List<ReportResultDB> queryDiseases(Map<String, Object> map);
	
	/**
	 * 服务费用下级区域概括
	 * @param map
	 * @return
	 */
//	List<reportResultDB> queryLower(Map<String, Object> map);
	/**
	 * 时间趋势-个体诊所人员构成概况分析
	 */
	Map<String, String> timeseriesPerson(RuquestBeanDTO ruquestBeanDTO);
	/**
	 * 合理用药-抗生素使用情况分析
	 */
	List<ReportResultDTO> antibioticUse(RuquestBeanDTO ruquestBeanDTO);
	/**
	 * 合理用药-输液情况
	 */
	List<ReportResult2DTO> transfusion(RuquestBeanDTO ruquestBeanDTO);

	/**
	 * 合理用药-输液处方抗生素占比
	 */
	List<ReportResultDB> antibioticTransfusion(RuquestBeanDTO ruquestBeanDTO);
	/**
	 * 合理用药-下级-各下级行政区划个体诊所抗生素使用占比
	 */
	List<ReportResultDB> roportionAntibioticUse(RuquestBeanDTO ruquestBeanDTO);
	/**
	 * 合理用药-下级-个体诊所输液处方占比
	 */
	List<ReportResultDB> transfusionPrescriptions(RuquestBeanDTO ruquestBeanDTO);
	/**
	 * 合理用药-时间趋势-抗生素处方占比变化情况
	 */
	List<ReportResultDB> antibioticTransfusionUse(RuquestBeanDTO ruquestBeanDTO);
	/**
	 * 合理用药-时间趋势-输液处方占比变化情况
	 */
	List<ReportResultDB> TransfusionUseCg(RuquestBeanDTO ruquestBeanDTO);
	/**
	 * 合理用药-情况信息总表
	 */
	List<ReportResultDB> RationalForm(RuquestBeanDTO ruquestBeanDTO);
	/**
	 * 医疗服务规范- 辖区总体概况
	 */
	List<ReportResultDTO> AreaGeneralSituation(RuquestBeanDTO ruquestBeanDTO);
	/**
	 * 医疗服务规范- 下级区划概况
	 */
	List<ReportResultDB> lowerRegion(RuquestBeanDTO ruquestBeanDTO);
	
	/**
	 * 查询前十的病种名称
	 * @param map
	 * @return
	 */
	List<ReportResultDB> queryFirstTenTown(Map<String, Object> map);
	
	
	/**
	 * 根据病种id查询该病种男女占比
	 * @param map
	 * @return
	 */
	List<ReportResultDB> queryFirstTentype(Map<String, Object> map);
	/**
	 * 资质监管
	 */
	ReportResultDB expire(RuquestBeanDTO ruquestBeanDTO);
	/**
	 * 资质监管-到期数量
	 * @return 过期的orgid总和
	 */
	List<Map<String, String>> listTimeClinics(RuquestBeanDTO ruquestBeanDTO);
	
	/**
	 * 个体诊所选择病种发病总量
	 * @param map
	 * @return
	 */
	List<ReportResultDB> queryGivenSummary(Map<String, Object> map);
	
	/**
	 * 特定病种高发地区分布
	 * @param map
	 * @return
	 */
	List<ReportResultDB> queryGivenFeatures(Map<String, Object> map);
	
	/**
	 * 个体诊所A病种发病性别或年龄分布
	 * @param map
	 * @return
	 */
	List<ReportResultDB> queryGivenSexOrAge(Map<String, Object> map);
	
	/**
	 * 时间趋势
	 */
	List<ReportResultDB> queryGivenTimeTrend(Map<String, Object> map);
	/**
	 *  个体诊所医疗质量情况概览
	 */
	List<ReportResultDB> OverviewClinicMedicalQuality(RuquestBeanDTO ruquestBeanDTO);
	/**
	 * 个体诊所医疗质量情况概览表单
	 */
	List<Map<String, String>> ListOverviewClinicMedicalQuality(RuquestBeanDTO ruquestBeanDTO);
	
	/**
	 * 2诊所资源-覆盖情况- 诊所医疗能力覆盖情况
	 * @param ruquestBeanDTO
	 * @return
	 */
	List<SmCliAreaCover> CoverageJson(RuquestBeanDTO ruquestBeanDTO);
	
	/**
	 * 根据病种id查询该病种年龄占比
	 * @param map
	 * @return
	 */
	List<ReportResultDB> queryFirstTentypes(Map<String, Object> map);
	
	/**
	 * 各种病种总和查询
	 * @param map
	 * @return
	 */
	List<ReportResultDB> queryFirstTenSum(Map<String, Object> map);
	
	/**
	 * 门诊总量
	 * @param map
	 * @return
	 */
	List<ReportResultDB> queryOperates(Map<String, Object> map);
}