package com.huatuo.clinics.cms.db.mapper;

import com.huatuo.clinics.cms.db.bean.SmCliAreaSicknessInfo;
import com.huatuo.clinics.cms.db.bean.SmCliAreaSicknessInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmCliAreaSicknessInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_sickness_info
     *
     * @mbggenerated Thu Aug 18 10:00:53 CST 2016
     */
    int countByExample(SmCliAreaSicknessInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_sickness_info
     *
     * @mbggenerated Thu Aug 18 10:00:53 CST 2016
     */
    int deleteByExample(SmCliAreaSicknessInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_sickness_info
     *
     * @mbggenerated Thu Aug 18 10:00:53 CST 2016
     */
    int deleteByPrimaryKey(String areaSicknessId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_sickness_info
     *
     * @mbggenerated Thu Aug 18 10:00:53 CST 2016
     */
    int insert(SmCliAreaSicknessInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_sickness_info
     *
     * @mbggenerated Thu Aug 18 10:00:53 CST 2016
     */
    int insertSelective(SmCliAreaSicknessInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_sickness_info
     *
     * @mbggenerated Thu Aug 18 10:00:53 CST 2016
     */
    List<SmCliAreaSicknessInfo> selectByExample(SmCliAreaSicknessInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_sickness_info
     *
     * @mbggenerated Thu Aug 18 10:00:53 CST 2016
     */
    SmCliAreaSicknessInfo selectByPrimaryKey(String areaSicknessId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_sickness_info
     *
     * @mbggenerated Thu Aug 18 10:00:53 CST 2016
     */
    int updateByExampleSelective(@Param("record") SmCliAreaSicknessInfo record, @Param("example") SmCliAreaSicknessInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_sickness_info
     *
     * @mbggenerated Thu Aug 18 10:00:53 CST 2016
     */
    int updateByExample(@Param("record") SmCliAreaSicknessInfo record, @Param("example") SmCliAreaSicknessInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_sickness_info
     *
     * @mbggenerated Thu Aug 18 10:00:53 CST 2016
     */
    int updateByPrimaryKeySelective(SmCliAreaSicknessInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_sickness_info
     *
     * @mbggenerated Thu Aug 18 10:00:53 CST 2016
     */
    int updateByPrimaryKey(SmCliAreaSicknessInfo record);
}