package com.huatuo.clinics.cms.db.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.huatuo.clinics.cms.db.bean.SsDicItem;
import com.huatuo.clinics.cms.db.bean.SsDicItemExample;

public interface SsDicItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_dic_item
     *
     * @mbggenerated Wed Mar 30 10:12:50 CST 2016
     */
    int countByExample(SsDicItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_dic_item
     *
     * @mbggenerated Wed Mar 30 10:12:50 CST 2016
     */
    int deleteByExample(SsDicItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_dic_item
     *
     * @mbggenerated Wed Mar 30 10:12:50 CST 2016
     */
    int deleteByPrimaryKey(String dictItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_dic_item
     *
     * @mbggenerated Wed Mar 30 10:12:50 CST 2016
     */
    int insert(SsDicItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_dic_item
     *
     * @mbggenerated Wed Mar 30 10:12:50 CST 2016
     */
    int insertSelective(SsDicItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_dic_item
     *
     * @mbggenerated Wed Mar 30 10:12:50 CST 2016
     */
    List<SsDicItem> selectByExample(SsDicItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_dic_item
     *
     * @mbggenerated Wed Mar 30 10:12:50 CST 2016
     */
    SsDicItem selectByPrimaryKey(String dictItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_dic_item
     *
     * @mbggenerated Wed Mar 30 10:12:50 CST 2016
     */
    int updateByExampleSelective(@Param("record") SsDicItem record, @Param("example") SsDicItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_dic_item
     *
     * @mbggenerated Wed Mar 30 10:12:50 CST 2016
     */
    int updateByExample(@Param("record") SsDicItem record, @Param("example") SsDicItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_dic_item
     *
     * @mbggenerated Wed Mar 30 10:12:50 CST 2016
     */
    int updateByPrimaryKeySelective(SsDicItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_dic_item
     *
     * @mbggenerated Wed Mar 30 10:12:50 CST 2016
     */
    int updateByPrimaryKey(SsDicItem record);
    
	/**
	 * 查询字典数据
	 */
	List<SsDicItem> getDicByCode(Map<String, Object> queryMap);
}