package com.huatuo.clinics.cms.db.mapper;

import com.huatuo.clinics.cms.db.bean.TaPhaDictDrugAntibioticLevelPolity;
import com.huatuo.clinics.cms.db.bean.TaPhaDictDrugAntibioticLevelPolityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TaPhaDictDrugAntibioticLevelPolityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ta_pha_dict_drug_antibiotic_level_polity
     *
     * @mbggenerated Thu Nov 17 10:42:07 CST 2016
     */
    int countByExample(TaPhaDictDrugAntibioticLevelPolityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ta_pha_dict_drug_antibiotic_level_polity
     *
     * @mbggenerated Thu Nov 17 10:42:07 CST 2016
     */
    int deleteByExample(TaPhaDictDrugAntibioticLevelPolityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ta_pha_dict_drug_antibiotic_level_polity
     *
     * @mbggenerated Thu Nov 17 10:42:07 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ta_pha_dict_drug_antibiotic_level_polity
     *
     * @mbggenerated Thu Nov 17 10:42:07 CST 2016
     */
    int insert(TaPhaDictDrugAntibioticLevelPolity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ta_pha_dict_drug_antibiotic_level_polity
     *
     * @mbggenerated Thu Nov 17 10:42:07 CST 2016
     */
    int insertSelective(TaPhaDictDrugAntibioticLevelPolity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ta_pha_dict_drug_antibiotic_level_polity
     *
     * @mbggenerated Thu Nov 17 10:42:07 CST 2016
     */
    List<TaPhaDictDrugAntibioticLevelPolity> selectByExample(TaPhaDictDrugAntibioticLevelPolityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ta_pha_dict_drug_antibiotic_level_polity
     *
     * @mbggenerated Thu Nov 17 10:42:07 CST 2016
     */
    TaPhaDictDrugAntibioticLevelPolity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ta_pha_dict_drug_antibiotic_level_polity
     *
     * @mbggenerated Thu Nov 17 10:42:07 CST 2016
     */
    int updateByExampleSelective(@Param("record") TaPhaDictDrugAntibioticLevelPolity record, @Param("example") TaPhaDictDrugAntibioticLevelPolityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ta_pha_dict_drug_antibiotic_level_polity
     *
     * @mbggenerated Thu Nov 17 10:42:07 CST 2016
     */
    int updateByExample(@Param("record") TaPhaDictDrugAntibioticLevelPolity record, @Param("example") TaPhaDictDrugAntibioticLevelPolityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ta_pha_dict_drug_antibiotic_level_polity
     *
     * @mbggenerated Thu Nov 17 10:42:07 CST 2016
     */
    int updateByPrimaryKeySelective(TaPhaDictDrugAntibioticLevelPolity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ta_pha_dict_drug_antibiotic_level_polity
     *
     * @mbggenerated Thu Nov 17 10:42:07 CST 2016
     */
    int updateByPrimaryKey(TaPhaDictDrugAntibioticLevelPolity record);
}