package com.huatuo.clinics.cms.db.mapper;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.huatuo.clinics.cms.db.bean.TaPhaDrugInventory;
import com.huatuo.clinics.cms.db.bean.TaPhaDrugInventoryExample;

public interface TaPhaDrugInventoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ta_pha_drug_inventory
     *
     * @mbggenerated Sat Aug 13 15:53:21 CST 2016
     */
    int countByExample(TaPhaDrugInventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ta_pha_drug_inventory
     *
     * @mbggenerated Sat Aug 13 15:53:21 CST 2016
     */
    int deleteByExample(TaPhaDrugInventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ta_pha_drug_inventory
     *
     * @mbggenerated Sat Aug 13 15:53:21 CST 2016
     */
    int deleteByPrimaryKey(String drugInvId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ta_pha_drug_inventory
     *
     * @mbggenerated Sat Aug 13 15:53:21 CST 2016
     */
    int insert(TaPhaDrugInventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ta_pha_drug_inventory
     *
     * @mbggenerated Sat Aug 13 15:53:21 CST 2016
     */
    int insertSelective(TaPhaDrugInventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ta_pha_drug_inventory
     *
     * @mbggenerated Sat Aug 13 15:53:21 CST 2016
     */
    List<TaPhaDrugInventory> selectByExample(TaPhaDrugInventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ta_pha_drug_inventory
     *
     * @mbggenerated Sat Aug 13 15:53:21 CST 2016
     */
    TaPhaDrugInventory selectByPrimaryKey(String drugInvId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ta_pha_drug_inventory
     *
     * @mbggenerated Sat Aug 13 15:53:21 CST 2016
     */
    int updateByExampleSelective(@Param("record") TaPhaDrugInventory record, @Param("example") TaPhaDrugInventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ta_pha_drug_inventory
     *
     * @mbggenerated Sat Aug 13 15:53:21 CST 2016
     */
    int updateByExample(@Param("record") TaPhaDrugInventory record, @Param("example") TaPhaDrugInventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ta_pha_drug_inventory
     *
     * @mbggenerated Sat Aug 13 15:53:21 CST 2016
     */
    int updateByPrimaryKeySelective(TaPhaDrugInventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ta_pha_drug_inventory
     *
     * @mbggenerated Sat Aug 13 15:53:21 CST 2016
     */
    int updateByPrimaryKey(TaPhaDrugInventory record);
    
    /**
     * 根据药品ID更新库存数量
     * @param record
     * @param example
     * @return
     */
    int updateByPhaDrugID(@Param("record") TaPhaDrugInventory record, @Param("example") TaPhaDrugInventoryExample example);
    
    
    /**
	 * 条数统计查询
	 * @param Drugtype 药用类型
	 * @param orgId    机构id
	 * @param pharmacyId 药房id
	 * @return
	 */
    int countList(Map<String,Object> map);
    
    /**
   	 * 条数统计查询
   	 * @param Drugtype 药用类型
   	 * @param orgId    机构id
   	 * @param pharmacyId 药房id
   	 * @return
   	 */
    int countListForKey(Map<String,Object> map);
       

    /**
     * 查询该药品下的首次批次
     * @param phaDrugId
     * @return
     */
	TaPhaDrugInventory queryByPhaDrugAndNum(Map<String,Object> map);
	
	/**
	 * 药品报损更新库存
	 * @param dto
	 * @return
	 */
	int updatePackQty(TaPhaDrugInventory dto);

	/**
	 * 为盘点的总数查询
	 */
	int countListForStocktaking(Map<String, Object> map);

	/**
	 * 为盘点的总数查询
	 */
	int countListByKeyForStocktaking(Map<String, Object> map);
	
	/**
	 * 拿取最近几次的最高收费包装价格
	 * @param map
	 * @return
	 */
	Float getMaxActualPrice(HashMap<String, Object> map);
	/**
	 * 拿取最近几次的最高收费包装价格
	 * @param map
	 * @return
	 */
	Float getMinActualPrice(HashMap<String, Object> map);
	/**
	 * 查询一种药品的所有库存
	 * @param map1
	 * @return
	 */
	List<TaPhaDrugInventory> getListPrice(HashMap<String, Object> map1);
    
}