package com.huatuo.clinics.cms.db.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.huatuo.clinics.cms.db.bean.XtLoginLog;
import com.huatuo.clinics.cms.db.bean.XtLoginLogExample;

public interface XtClinicsLoginLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_login_log
     *
     * @mbggenerated Wed Aug 02 15:03:40 CST 2017
     */
    int countByExample(XtLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_login_log
     *
     * @mbggenerated Wed Aug 02 15:03:40 CST 2017
     */
    int deleteByExample(XtLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_login_log
     *
     * @mbggenerated Wed Aug 02 15:03:40 CST 2017
     */
    int deleteByPrimaryKey(String loginLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_login_log
     *
     * @mbggenerated Wed Aug 02 15:03:40 CST 2017
     */
    int insert(XtLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_login_log
     *
     * @mbggenerated Wed Aug 02 15:03:40 CST 2017
     */
    int insertSelective(XtLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_login_log
     *
     * @mbggenerated Wed Aug 02 15:03:40 CST 2017
     */
    List<XtLoginLog> selectByExample(XtLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_login_log
     *
     * @mbggenerated Wed Aug 02 15:03:40 CST 2017
     */
    XtLoginLog selectByPrimaryKey(String loginLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_login_log
     *
     * @mbggenerated Wed Aug 02 15:03:40 CST 2017
     */
    int updateByExampleSelective(@Param("record") XtLoginLog record, @Param("example") XtLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_login_log
     *
     * @mbggenerated Wed Aug 02 15:03:40 CST 2017
     */
    int updateByExample(@Param("record") XtLoginLog record, @Param("example") XtLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_login_log
     *
     * @mbggenerated Wed Aug 02 15:03:40 CST 2017
     */
    int updateByPrimaryKeySelective(XtLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_login_log
     *
     * @mbggenerated Wed Aug 02 15:03:40 CST 2017
     */
    int updateByPrimaryKey(XtLoginLog record);

    /**
     * 通过时间，机构id获得机构登录日志列表
     * @param map
     * @return
     */
	List<XtLoginLog> getListByOrgId(Map<String, Object> map);
}