package com.huatuo.clinics.cms.bean;

import com.huatuo.clinics.cms.services.translate.Translatable;
import com.huatuo.clinics.cms.services.translate.TranslateField;

public class CsOutpOrderDtlDTO<T> implements Translatable{
	private String ordDtlId;//处方明细id
    private String ordId;//医嘱id
    private Integer itemNo;//明细序号
    private Integer vistiNo;//就诊编号
    private String groupNo;//组号
    @TranslateField(fullQualifiedName="20107",targetFieldName="ordTypeName")
    private String ordType;//药品类型：西药/中成药、中草药、诊疗项
    private String ordTypeName;//药品类型：西药/中成药、中草药、诊疗项
    private String ordItemId;//诊疗id/药品id
    private String clinicalItemSpec;//诊疗项目规格
    private Integer sortNo;//排序序号
    private Float defDoseQty;//剂量
    @TranslateField(fullQualifiedName="32103,32104",targetFieldName="defDoseUnitName")
    private String defDoseUnit;//剂量单位
    private String defDoseUnitName;//剂量单位名称
    private Float dosage;//单次用量
    @TranslateField(fullQualifiedName="32102,32104",targetFieldName="dosageUnitName")
    private String dosageUnit;//单次用量单位
    private String dosageUnitName;//单次用量单位名称
    private Integer backQty;//退回数量
    private Integer buyQty;//购买数量
    @TranslateField(fullQualifiedName="32102,32104",targetFieldName="buyUnitName")
    private String buyUnit;//购买单位
    private String buyUnitName;//购买单位
    private String doctorId;//医生
    private String orderMemo;//嘱托
    @TranslateField(fullQualifiedName="90005,90007",targetFieldName="routeName")
    private String route;//给药方式
    private String routeName;//给药方式
    @TranslateField(fullQualifiedName="90004",targetFieldName="freqName")
    private String freq;//服药频率
    private String freqName;//服药频率
    private Integer repetition;//付数
    private Integer days; //天数
    private Integer convQty; //换算量
    private Float itemPrice; //自定义诊疗项价格
    
//    //自定义字段
    private Float subtotal;//小计
    private Integer beforeBackQty;//前台退回数量
    private Integer residueBackQty;//剩余可退数量
    private String tradeName;//药品名或者诊疗项目名
    private Float packRetailPrice;//零售价或者诊疗价（判断购买单位符合那个单位，提取相应的价格）
    private Float minRetailPrice;//小单位市场零售价
    @TranslateField(fullQualifiedName="32102",targetFieldName="minUnitName")
    private String minUnit;//最小包装单位
    private String minUnitName;
    @TranslateField(fullQualifiedName="32102",targetFieldName="packUnitName")
    private String packUnit;//包装单位
    private String packUnitName;
    
    private Float weight;//重量
    private Float volume;//体积
    
    //通过判断orderType处方类型（中药；草药；诊疗收费）
    private T t; 
    
    public T getT() {
		return t;
	}

	public Float getWeight() {
		return weight;
	}

	public void setWeight(Float weight) {
		this.weight = weight;
	}

	public Float getVolume() {
		return volume;
	}

	public void setVolume(Float volume) {
		this.volume = volume;
	}

	public String getDosageUnitName() {
		return dosageUnitName;
	}

	public void setDosageUnitName(String dosageUnitName) {
		this.dosageUnitName = dosageUnitName;
	}

	public String getBuyUnitName() {
		return buyUnitName;
	}

	public void setBuyUnitName(String buyUnitName) {
		this.buyUnitName = buyUnitName;
	}

	public Integer getBackQty() {
		return backQty;
	}

	public void setBackQty(Integer backQty) {
		this.backQty = backQty;
	}

	public Integer getDays() {
		return days;
	}

	public void setDays(Integer days) {
		this.days = days;
	}

	public Integer getBeforeBackQty() {
		return beforeBackQty;
	}

	public void setBeforeBackQty(Integer beforeBackQty) {
		this.beforeBackQty = beforeBackQty;
	}

	public Integer getResidueBackQty() {
		return residueBackQty;
	}

	public void setResidueBackQty(Integer residueBackQty) {
		this.residueBackQty = residueBackQty;
	}

	public String getOrdTypeName() {
		return ordTypeName;
	}

	public void setOrdTypeName(String ordTypeName) {
		this.ordTypeName = ordTypeName;
	}

	public String getRouteName() {
		return routeName;
	}

	public void setRouteName(String routeName) {
		this.routeName = routeName;
	}

	public String getFreqName() {
		return freqName;
	}

	public void setFreqName(String freqName) {
		this.freqName = freqName;
	}

	public Float getSubtotal() {
		return subtotal;
	}

	public void setSubtotal(Float subtotal) {
		this.subtotal = subtotal;
	}

	public void setT(T t) {
		this.t = t;
	}

	public String getOrdDtlId() {
        return ordDtlId;
    }

	public String getTradeName() {
		return tradeName;
	}

	public void setTradeName(String tradeName) {
		this.tradeName = tradeName;
	}

	public Float getPackRetailPrice() {
		return packRetailPrice;
	}

	public void setPackRetailPrice(Float packRetailPrice) {
		this.packRetailPrice = packRetailPrice;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_outp_order_dtl.ord_dtl_id
     *
     * @param ordDtlId the value for cs_outp_order_dtl.ord_dtl_id
     *
     * @mbggenerated Wed Mar 16 14:12:58 CST 2016
     */
    public void setOrdDtlId(String ordDtlId) {
        this.ordDtlId = ordDtlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_outp_order_dtl.ord_id
     *
     * @return the value of cs_outp_order_dtl.ord_id
     *
     * @mbggenerated Wed Mar 16 14:12:58 CST 2016
     */
    public String getOrdId() {
        return ordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_outp_order_dtl.ord_id
     *
     * @param ordId the value for cs_outp_order_dtl.ord_id
     *
     * @mbggenerated Wed Mar 16 14:12:58 CST 2016
     */
    public void setOrdId(String ordId) {
        this.ordId = ordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_outp_order_dtl.item_no
     *
     * @return the value of cs_outp_order_dtl.item_no
     *
     * @mbggenerated Wed Mar 16 14:12:58 CST 2016
     */
    public Integer getItemNo() {
        return itemNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_outp_order_dtl.item_no
     *
     * @param itemNo the value for cs_outp_order_dtl.item_no
     *
     * @mbggenerated Wed Mar 16 14:12:58 CST 2016
     */
    public void setItemNo(Integer itemNo) {
        this.itemNo = itemNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_outp_order_dtl.visti_no
     *
     * @return the value of cs_outp_order_dtl.visti_no
     *
     * @mbggenerated Wed Mar 16 14:12:58 CST 2016
     */
    public Integer getVistiNo() {
        return vistiNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_outp_order_dtl.visti_no
     *
     * @param vistiNo the value for cs_outp_order_dtl.visti_no
     *
     * @mbggenerated Wed Mar 16 14:12:58 CST 2016
     */
    public void setVistiNo(Integer vistiNo) {
        this.vistiNo = vistiNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_outp_order_dtl.group_no
     *
     * @return the value of cs_outp_order_dtl.group_no
     *
     * @mbggenerated Wed Mar 16 14:12:58 CST 2016
     */
    public String getGroupNo() {
        return groupNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_outp_order_dtl.group_no
     *
     * @param groupNo the value for cs_outp_order_dtl.group_no
     *
     * @mbggenerated Wed Mar 16 14:12:58 CST 2016
     */
    public void setGroupNo(String groupNo) {
        this.groupNo = groupNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_outp_order_dtl.ord_type
     *
     * @return the value of cs_outp_order_dtl.ord_type
     *
     * @mbggenerated Wed Mar 16 14:12:58 CST 2016
     */
    public String getOrdType() {
        return ordType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_outp_order_dtl.ord_type
     *
     * @param ordType the value for cs_outp_order_dtl.ord_type
     *
     * @mbggenerated Wed Mar 16 14:12:58 CST 2016
     */
    public void setOrdType(String ordType) {
        this.ordType = ordType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_outp_order_dtl.ord_item_id
     *
     * @return the value of cs_outp_order_dtl.ord_item_id
     *
     * @mbggenerated Wed Mar 16 14:12:58 CST 2016
     */
    public String getOrdItemId() {
        return ordItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_outp_order_dtl.ord_item_id
     *
     * @param ordItemId the value for cs_outp_order_dtl.ord_item_id
     *
     * @mbggenerated Wed Mar 16 14:12:58 CST 2016
     */
    public void setOrdItemId(String ordItemId) {
        this.ordItemId = ordItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_outp_order_dtl.clinical_item_spec
     *
     * @return the value of cs_outp_order_dtl.clinical_item_spec
     *
     * @mbggenerated Wed Mar 16 14:12:58 CST 2016
     */
    public String getClinicalItemSpec() {
        return clinicalItemSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_outp_order_dtl.clinical_item_spec
     *
     * @param clinicalItemSpec the value for cs_outp_order_dtl.clinical_item_spec
     *
     * @mbggenerated Wed Mar 16 14:12:58 CST 2016
     */
    public void setClinicalItemSpec(String clinicalItemSpec) {
        this.clinicalItemSpec = clinicalItemSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_outp_order_dtl.sort_no
     *
     * @return the value of cs_outp_order_dtl.sort_no
     *
     * @mbggenerated Wed Mar 16 14:12:58 CST 2016
     */
    public Integer getSortNo() {
        return sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_outp_order_dtl.sort_no
     *
     * @param sortNo the value for cs_outp_order_dtl.sort_no
     *
     * @mbggenerated Wed Mar 16 14:12:58 CST 2016
     */
    public void setSortNo(Integer sortNo) {
        this.sortNo = sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_outp_order_dtl.dosage
     *
     * @return the value of cs_outp_order_dtl.dosage
     *
     * @mbggenerated Wed Mar 16 14:12:58 CST 2016
     */
    public Float getDosage() {
        return dosage;
    }
    public void setDosage(Float dosage) {
        this.dosage = dosage;
    }
    public String getDosageUnit() {
        return dosageUnit;
    }
    public void setDosageUnit(String dosageUnit) {
        this.dosageUnit = dosageUnit;
    }
    public Integer getBuyQty() {
        return buyQty;
    }
    public void setBuyQty(Integer buyQty) {
        this.buyQty = buyQty;
    }
    public String getBuyUnit() {
        return buyUnit;
    }
    public void setBuyUnit(String buyUnit) {
        this.buyUnit = buyUnit;
    }
    public String getDoctorId() {
        return doctorId;
    }
    public void setDoctorId(String doctorId) {
        this.doctorId = doctorId;
    }
    public String getOrderMemo() {
        return orderMemo;
    }
    public void setOrderMemo(String orderMemo) {
        this.orderMemo = orderMemo;
    }
    public String getRoute() {
        return route;
    }
    public void setRoute(String route) {
        this.route = route;
    }
    public String getFreq() {
        return freq;
    }
    public void setFreq(String freq) {
        this.freq = freq;
    }
    public Integer getRepetition() {
        return repetition;
    }
    public void setRepetition(Integer repetition) {
        this.repetition = repetition;
    }
	public Integer getConvQty() {
		return convQty;
	}

	public void setConvQty(Integer convQty) {
		this.convQty = convQty;
	}

	public Float getDefDoseQty() {
		return defDoseQty;
	}

	public void setDefDoseQty(Float defDoseQty) {
		this.defDoseQty = defDoseQty;
	}

	public String getDefDoseUnit() {
		return defDoseUnit;
	}

	public void setDefDoseUnit(String defDoseUnit) {
		this.defDoseUnit = defDoseUnit;
	}

	public String getMinUnit() {
		return minUnit;
	}

	public void setMinUnit(String minUnit) {
		this.minUnit = minUnit;
	}

	public String getMinUnitName() {
		return minUnitName;
	}

	public void setMinUnitName(String minUnitName) {
		this.minUnitName = minUnitName;
	}

	public String getPackUnit() {
		return packUnit;
	}

	public void setPackUnit(String packUnit) {
		this.packUnit = packUnit;
	}

	public String getPackUnitName() {
		return packUnitName;
	}

	public void setPackUnitName(String packUnitName) {
		this.packUnitName = packUnitName;
	}

	public String getDefDoseUnitName() {
		return defDoseUnitName;
	}

	public void setDefDoseUnitName(String defDoseUnitName) {
		this.defDoseUnitName = defDoseUnitName;
	}

	public Float getItemPrice() {
		return itemPrice;
	}

	public void setItemPrice(Float itemPrice) {
		this.itemPrice = itemPrice;
	}

	public Float getMinRetailPrice() {
		return minRetailPrice;
	}

	public void setMinRetailPrice(Float minRetailPrice) {
		this.minRetailPrice = minRetailPrice;
	}
}