package com.huatuo.clinics.cms.db.bean;

public class CmPerReportDefend {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_per_report_defend.id
     *
     * @mbggenerated Sat Oct 29 10:31:19 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_per_report_defend.type
     *
     * @mbggenerated Sat Oct 29 10:31:19 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_per_report_defend.org_id
     *
     * @mbggenerated Sat Oct 29 10:31:19 CST 2016
     */
    private String orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_per_report_defend.print
     *
     * @mbggenerated Sat Oct 29 10:31:19 CST 2016
     */
    private String print;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_per_report_defend.print_name
     *
     * @mbggenerated Sat Oct 29 10:31:19 CST 2016
     */
    private String printName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_per_report_defend.not_print
     *
     * @mbggenerated Sat Oct 29 10:31:19 CST 2016
     */
    private String notPrint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_per_report_defend.not_print_name
     *
     * @mbggenerated Sat Oct 29 10:31:19 CST 2016
     */
    private String notPrintName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_per_report_defend.actual_name
     *
     * @mbggenerated Sat Oct 29 10:31:19 CST 2016
     */
    private String actualName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_per_report_defend.memo
     *
     * @mbggenerated Sat Oct 29 10:31:19 CST 2016
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_per_report_defend.valid_flg
     *
     * @mbggenerated Sat Oct 29 10:31:19 CST 2016
     */
    private String validFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_per_report_defend.default_type
     *
     * @mbggenerated Sat Oct 29 10:31:19 CST 2016
     */
    private String defaultType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_per_report_defend.id
     *
     * @return the value of cm_per_report_defend.id
     *
     * @mbggenerated Sat Oct 29 10:31:19 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_per_report_defend.id
     *
     * @param id the value for cm_per_report_defend.id
     *
     * @mbggenerated Sat Oct 29 10:31:19 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_per_report_defend.type
     *
     * @return the value of cm_per_report_defend.type
     *
     * @mbggenerated Sat Oct 29 10:31:19 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_per_report_defend.type
     *
     * @param type the value for cm_per_report_defend.type
     *
     * @mbggenerated Sat Oct 29 10:31:19 CST 2016
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_per_report_defend.org_id
     *
     * @return the value of cm_per_report_defend.org_id
     *
     * @mbggenerated Sat Oct 29 10:31:19 CST 2016
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_per_report_defend.org_id
     *
     * @param orgId the value for cm_per_report_defend.org_id
     *
     * @mbggenerated Sat Oct 29 10:31:19 CST 2016
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_per_report_defend.print
     *
     * @return the value of cm_per_report_defend.print
     *
     * @mbggenerated Sat Oct 29 10:31:19 CST 2016
     */
    public String getPrint() {
        return print;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_per_report_defend.print
     *
     * @param print the value for cm_per_report_defend.print
     *
     * @mbggenerated Sat Oct 29 10:31:19 CST 2016
     */
    public void setPrint(String print) {
        this.print = print;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_per_report_defend.print_name
     *
     * @return the value of cm_per_report_defend.print_name
     *
     * @mbggenerated Sat Oct 29 10:31:19 CST 2016
     */
    public String getPrintName() {
        return printName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_per_report_defend.print_name
     *
     * @param printName the value for cm_per_report_defend.print_name
     *
     * @mbggenerated Sat Oct 29 10:31:19 CST 2016
     */
    public void setPrintName(String printName) {
        this.printName = printName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_per_report_defend.not_print
     *
     * @return the value of cm_per_report_defend.not_print
     *
     * @mbggenerated Sat Oct 29 10:31:19 CST 2016
     */
    public String getNotPrint() {
        return notPrint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_per_report_defend.not_print
     *
     * @param notPrint the value for cm_per_report_defend.not_print
     *
     * @mbggenerated Sat Oct 29 10:31:19 CST 2016
     */
    public void setNotPrint(String notPrint) {
        this.notPrint = notPrint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_per_report_defend.not_print_name
     *
     * @return the value of cm_per_report_defend.not_print_name
     *
     * @mbggenerated Sat Oct 29 10:31:19 CST 2016
     */
    public String getNotPrintName() {
        return notPrintName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_per_report_defend.not_print_name
     *
     * @param notPrintName the value for cm_per_report_defend.not_print_name
     *
     * @mbggenerated Sat Oct 29 10:31:19 CST 2016
     */
    public void setNotPrintName(String notPrintName) {
        this.notPrintName = notPrintName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_per_report_defend.actual_name
     *
     * @return the value of cm_per_report_defend.actual_name
     *
     * @mbggenerated Sat Oct 29 10:31:19 CST 2016
     */
    public String getActualName() {
        return actualName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_per_report_defend.actual_name
     *
     * @param actualName the value for cm_per_report_defend.actual_name
     *
     * @mbggenerated Sat Oct 29 10:31:19 CST 2016
     */
    public void setActualName(String actualName) {
        this.actualName = actualName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_per_report_defend.memo
     *
     * @return the value of cm_per_report_defend.memo
     *
     * @mbggenerated Sat Oct 29 10:31:19 CST 2016
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_per_report_defend.memo
     *
     * @param memo the value for cm_per_report_defend.memo
     *
     * @mbggenerated Sat Oct 29 10:31:19 CST 2016
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_per_report_defend.valid_flg
     *
     * @return the value of cm_per_report_defend.valid_flg
     *
     * @mbggenerated Sat Oct 29 10:31:19 CST 2016
     */
    public String getValidFlg() {
        return validFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_per_report_defend.valid_flg
     *
     * @param validFlg the value for cm_per_report_defend.valid_flg
     *
     * @mbggenerated Sat Oct 29 10:31:19 CST 2016
     */
    public void setValidFlg(String validFlg) {
        this.validFlg = validFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_per_report_defend.default_type
     *
     * @return the value of cm_per_report_defend.default_type
     *
     * @mbggenerated Sat Oct 29 10:31:19 CST 2016
     */
    public String getDefaultType() {
        return defaultType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_per_report_defend.default_type
     *
     * @param defaultType the value for cm_per_report_defend.default_type
     *
     * @mbggenerated Sat Oct 29 10:31:19 CST 2016
     */
    public void setDefaultType(String defaultType) {
        this.defaultType = defaultType;
    }
}