package com.huatuo.clinics.cms.db.bean;

public class CmsJgMonitor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_jg_monitor.id
     *
     * @mbggenerated Wed Nov 16 16:05:54 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_jg_monitor.org_id
     *
     * @mbggenerated Wed Nov 16 16:05:54 CST 2016
     */
    private String orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_jg_monitor.org_name
     *
     * @mbggenerated Wed Nov 16 16:05:54 CST 2016
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_jg_monitor.type_id
     *
     * @mbggenerated Wed Nov 16 16:05:54 CST 2016
     */
    private String typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_jg_monitor.date
     *
     * @mbggenerated Wed Nov 16 16:05:54 CST 2016
     */
    private String date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_jg_monitor.addressId
     *
     * @mbggenerated Wed Nov 16 16:05:54 CST 2016
     */
    private String addressid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_jg_monitor.address
     *
     * @mbggenerated Wed Nov 16 16:05:54 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_jg_monitor.type
     *
     * @mbggenerated Wed Nov 16 16:05:54 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_jg_monitor.address_dtl
     *
     * @mbggenerated Wed Nov 16 16:05:54 CST 2016
     */
    private String addressDtl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_jg_monitor.ebent_dtl
     *
     * @mbggenerated Wed Nov 16 16:05:54 CST 2016
     */
    private String ebentDtl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_jg_monitor.is_del
     *
     * @mbggenerated Wed Nov 16 16:05:54 CST 2016
     */
    private Integer isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_jg_monitor.id
     *
     * @return the value of cms_jg_monitor.id
     *
     * @mbggenerated Wed Nov 16 16:05:54 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_jg_monitor.id
     *
     * @param id the value for cms_jg_monitor.id
     *
     * @mbggenerated Wed Nov 16 16:05:54 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_jg_monitor.org_id
     *
     * @return the value of cms_jg_monitor.org_id
     *
     * @mbggenerated Wed Nov 16 16:05:54 CST 2016
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_jg_monitor.org_id
     *
     * @param orgId the value for cms_jg_monitor.org_id
     *
     * @mbggenerated Wed Nov 16 16:05:54 CST 2016
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_jg_monitor.org_name
     *
     * @return the value of cms_jg_monitor.org_name
     *
     * @mbggenerated Wed Nov 16 16:05:54 CST 2016
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_jg_monitor.org_name
     *
     * @param orgName the value for cms_jg_monitor.org_name
     *
     * @mbggenerated Wed Nov 16 16:05:54 CST 2016
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_jg_monitor.type_id
     *
     * @return the value of cms_jg_monitor.type_id
     *
     * @mbggenerated Wed Nov 16 16:05:54 CST 2016
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_jg_monitor.type_id
     *
     * @param typeId the value for cms_jg_monitor.type_id
     *
     * @mbggenerated Wed Nov 16 16:05:54 CST 2016
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_jg_monitor.date
     *
     * @return the value of cms_jg_monitor.date
     *
     * @mbggenerated Wed Nov 16 16:05:54 CST 2016
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_jg_monitor.date
     *
     * @param date the value for cms_jg_monitor.date
     *
     * @mbggenerated Wed Nov 16 16:05:54 CST 2016
     */
    public void setDate(String date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_jg_monitor.addressId
     *
     * @return the value of cms_jg_monitor.addressId
     *
     * @mbggenerated Wed Nov 16 16:05:54 CST 2016
     */
    public String getAddressid() {
        return addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_jg_monitor.addressId
     *
     * @param addressid the value for cms_jg_monitor.addressId
     *
     * @mbggenerated Wed Nov 16 16:05:54 CST 2016
     */
    public void setAddressid(String addressid) {
        this.addressid = addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_jg_monitor.address
     *
     * @return the value of cms_jg_monitor.address
     *
     * @mbggenerated Wed Nov 16 16:05:54 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_jg_monitor.address
     *
     * @param address the value for cms_jg_monitor.address
     *
     * @mbggenerated Wed Nov 16 16:05:54 CST 2016
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_jg_monitor.type
     *
     * @return the value of cms_jg_monitor.type
     *
     * @mbggenerated Wed Nov 16 16:05:54 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_jg_monitor.type
     *
     * @param type the value for cms_jg_monitor.type
     *
     * @mbggenerated Wed Nov 16 16:05:54 CST 2016
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_jg_monitor.address_dtl
     *
     * @return the value of cms_jg_monitor.address_dtl
     *
     * @mbggenerated Wed Nov 16 16:05:54 CST 2016
     */
    public String getAddressDtl() {
        return addressDtl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_jg_monitor.address_dtl
     *
     * @param addressDtl the value for cms_jg_monitor.address_dtl
     *
     * @mbggenerated Wed Nov 16 16:05:54 CST 2016
     */
    public void setAddressDtl(String addressDtl) {
        this.addressDtl = addressDtl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_jg_monitor.ebent_dtl
     *
     * @return the value of cms_jg_monitor.ebent_dtl
     *
     * @mbggenerated Wed Nov 16 16:05:54 CST 2016
     */
    public String getEbentDtl() {
        return ebentDtl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_jg_monitor.ebent_dtl
     *
     * @param ebentDtl the value for cms_jg_monitor.ebent_dtl
     *
     * @mbggenerated Wed Nov 16 16:05:54 CST 2016
     */
    public void setEbentDtl(String ebentDtl) {
        this.ebentDtl = ebentDtl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_jg_monitor.is_del
     *
     * @return the value of cms_jg_monitor.is_del
     *
     * @mbggenerated Wed Nov 16 16:05:54 CST 2016
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_jg_monitor.is_del
     *
     * @param isDel the value for cms_jg_monitor.is_del
     *
     * @mbggenerated Wed Nov 16 16:05:54 CST 2016
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }
}