package com.huatuo.clinics.cms.db.bean;

import java.util.Date;

public class CmsJgUserinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_jg_userinfo.id
     *
     * @mbggenerated Thu Oct 20 11:57:03 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_jg_userinfo.user_name
     *
     * @mbggenerated Thu Oct 20 11:57:03 CST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_jg_userinfo.pwd
     *
     * @mbggenerated Thu Oct 20 11:57:03 CST 2016
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_jg_userinfo.company
     *
     * @mbggenerated Thu Oct 20 11:57:03 CST 2016
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_jg_userinfo.cid
     *
     * @mbggenerated Thu Oct 20 11:57:03 CST 2016
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_jg_userinfo.create_time
     *
     * @mbggenerated Thu Oct 20 11:57:03 CST 2016
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_jg_userinfo.is_del
     *
     * @mbggenerated Thu Oct 20 11:57:03 CST 2016
     */
    private Integer isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_jg_userinfo.end_date
     *
     * @mbggenerated Thu Oct 20 11:57:03 CST 2016
     */
    private Date endDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_jg_userinfo.id
     *
     * @return the value of cms_jg_userinfo.id
     *
     * @mbggenerated Thu Oct 20 11:57:03 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_jg_userinfo.id
     *
     * @param id the value for cms_jg_userinfo.id
     *
     * @mbggenerated Thu Oct 20 11:57:03 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_jg_userinfo.user_name
     *
     * @return the value of cms_jg_userinfo.user_name
     *
     * @mbggenerated Thu Oct 20 11:57:03 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_jg_userinfo.user_name
     *
     * @param userName the value for cms_jg_userinfo.user_name
     *
     * @mbggenerated Thu Oct 20 11:57:03 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_jg_userinfo.pwd
     *
     * @return the value of cms_jg_userinfo.pwd
     *
     * @mbggenerated Thu Oct 20 11:57:03 CST 2016
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_jg_userinfo.pwd
     *
     * @param pwd the value for cms_jg_userinfo.pwd
     *
     * @mbggenerated Thu Oct 20 11:57:03 CST 2016
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_jg_userinfo.company
     *
     * @return the value of cms_jg_userinfo.company
     *
     * @mbggenerated Thu Oct 20 11:57:03 CST 2016
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_jg_userinfo.company
     *
     * @param company the value for cms_jg_userinfo.company
     *
     * @mbggenerated Thu Oct 20 11:57:03 CST 2016
     */
    public void setCompany(String company) {
        this.company = company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_jg_userinfo.cid
     *
     * @return the value of cms_jg_userinfo.cid
     *
     * @mbggenerated Thu Oct 20 11:57:03 CST 2016
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_jg_userinfo.cid
     *
     * @param cid the value for cms_jg_userinfo.cid
     *
     * @mbggenerated Thu Oct 20 11:57:03 CST 2016
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_jg_userinfo.create_time
     *
     * @return the value of cms_jg_userinfo.create_time
     *
     * @mbggenerated Thu Oct 20 11:57:03 CST 2016
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_jg_userinfo.create_time
     *
     * @param createTime the value for cms_jg_userinfo.create_time
     *
     * @mbggenerated Thu Oct 20 11:57:03 CST 2016
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_jg_userinfo.is_del
     *
     * @return the value of cms_jg_userinfo.is_del
     *
     * @mbggenerated Thu Oct 20 11:57:03 CST 2016
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_jg_userinfo.is_del
     *
     * @param isDel the value for cms_jg_userinfo.is_del
     *
     * @mbggenerated Thu Oct 20 11:57:03 CST 2016
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_jg_userinfo.end_date
     *
     * @return the value of cms_jg_userinfo.end_date
     *
     * @mbggenerated Thu Oct 20 11:57:03 CST 2016
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_jg_userinfo.end_date
     *
     * @param endDate the value for cms_jg_userinfo.end_date
     *
     * @mbggenerated Thu Oct 20 11:57:03 CST 2016
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
}