package com.huatuo.clinics.cms.db.bean;

public class CmsJgOrdercheck {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_jg_ordercheck.check_id
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    private String checkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_jg_ordercheck.check_date
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    private String checkDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_jg_ordercheck.check_area
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    private String checkArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_jg_ordercheck.org_id
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    private String orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_jg_ordercheck.org_name
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_jg_ordercheck.order_type
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    private String orderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_jg_ordercheck.check_count
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    private Integer checkCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_jg_ordercheck.qualified
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    private String qualified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_jg_ordercheck.qualified_no
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    private Integer qualifiedNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_jg_ordercheck.Unqualified_no
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    private Integer unqualifiedNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_jg_ordercheck.user_id
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_jg_ordercheck.user_name
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_jg_ordercheck.check_time
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    private String checkTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_jg_ordercheck.check_id
     *
     * @return the value of cms_jg_ordercheck.check_id
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    public String getCheckId() {
        return checkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_jg_ordercheck.check_id
     *
     * @param checkId the value for cms_jg_ordercheck.check_id
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    public void setCheckId(String checkId) {
        this.checkId = checkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_jg_ordercheck.check_date
     *
     * @return the value of cms_jg_ordercheck.check_date
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    public String getCheckDate() {
        return checkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_jg_ordercheck.check_date
     *
     * @param checkDate the value for cms_jg_ordercheck.check_date
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    public void setCheckDate(String checkDate) {
        this.checkDate = checkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_jg_ordercheck.check_area
     *
     * @return the value of cms_jg_ordercheck.check_area
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    public String getCheckArea() {
        return checkArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_jg_ordercheck.check_area
     *
     * @param checkArea the value for cms_jg_ordercheck.check_area
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    public void setCheckArea(String checkArea) {
        this.checkArea = checkArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_jg_ordercheck.org_id
     *
     * @return the value of cms_jg_ordercheck.org_id
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_jg_ordercheck.org_id
     *
     * @param orgId the value for cms_jg_ordercheck.org_id
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_jg_ordercheck.org_name
     *
     * @return the value of cms_jg_ordercheck.org_name
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_jg_ordercheck.org_name
     *
     * @param orgName the value for cms_jg_ordercheck.org_name
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_jg_ordercheck.order_type
     *
     * @return the value of cms_jg_ordercheck.order_type
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_jg_ordercheck.order_type
     *
     * @param orderType the value for cms_jg_ordercheck.order_type
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_jg_ordercheck.check_count
     *
     * @return the value of cms_jg_ordercheck.check_count
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    public Integer getCheckCount() {
        return checkCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_jg_ordercheck.check_count
     *
     * @param checkCount the value for cms_jg_ordercheck.check_count
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    public void setCheckCount(Integer checkCount) {
        this.checkCount = checkCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_jg_ordercheck.qualified
     *
     * @return the value of cms_jg_ordercheck.qualified
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    public String getQualified() {
        return qualified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_jg_ordercheck.qualified
     *
     * @param qualified the value for cms_jg_ordercheck.qualified
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    public void setQualified(String qualified) {
        this.qualified = qualified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_jg_ordercheck.qualified_no
     *
     * @return the value of cms_jg_ordercheck.qualified_no
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    public Integer getQualifiedNo() {
        return qualifiedNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_jg_ordercheck.qualified_no
     *
     * @param qualifiedNo the value for cms_jg_ordercheck.qualified_no
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    public void setQualifiedNo(Integer qualifiedNo) {
        this.qualifiedNo = qualifiedNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_jg_ordercheck.Unqualified_no
     *
     * @return the value of cms_jg_ordercheck.Unqualified_no
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    public Integer getUnqualifiedNo() {
        return unqualifiedNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_jg_ordercheck.Unqualified_no
     *
     * @param unqualifiedNo the value for cms_jg_ordercheck.Unqualified_no
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    public void setUnqualifiedNo(Integer unqualifiedNo) {
        this.unqualifiedNo = unqualifiedNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_jg_ordercheck.user_id
     *
     * @return the value of cms_jg_ordercheck.user_id
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_jg_ordercheck.user_id
     *
     * @param userId the value for cms_jg_ordercheck.user_id
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_jg_ordercheck.user_name
     *
     * @return the value of cms_jg_ordercheck.user_name
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_jg_ordercheck.user_name
     *
     * @param userName the value for cms_jg_ordercheck.user_name
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_jg_ordercheck.check_time
     *
     * @return the value of cms_jg_ordercheck.check_time
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    public String getCheckTime() {
        return checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_jg_ordercheck.check_time
     *
     * @param checkTime the value for cms_jg_ordercheck.check_time
     *
     * @mbggenerated Mon Oct 10 11:25:22 CST 2016
     */
    public void setCheckTime(String checkTime) {
        this.checkTime = checkTime;
    }
}