package com.huatuo.clinics.cms.db.bean;

public class CmsJgAddress {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_jg_address.address_id
     *
     * @mbggenerated Mon Aug 08 09:39:39 CST 2016
     */
    private String addressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_jg_address.province_code
     *
     * @mbggenerated Mon Aug 08 09:39:39 CST 2016
     */
    private Double provinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_jg_address.province
     *
     * @mbggenerated Mon Aug 08 09:39:39 CST 2016
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_jg_address.city_code
     *
     * @mbggenerated Mon Aug 08 09:39:39 CST 2016
     */
    private Double cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_jg_address.city
     *
     * @mbggenerated Mon Aug 08 09:39:39 CST 2016
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_jg_address.county_code
     *
     * @mbggenerated Mon Aug 08 09:39:39 CST 2016
     */
    private Double countyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_jg_address.county
     *
     * @mbggenerated Mon Aug 08 09:39:39 CST 2016
     */
    private String county;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_jg_address.road_code
     *
     * @mbggenerated Mon Aug 08 09:39:39 CST 2016
     */
    private Double roadCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_jg_address.road
     *
     * @mbggenerated Mon Aug 08 09:39:39 CST 2016
     */
    private String road;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_jg_address.address
     *
     * @mbggenerated Mon Aug 08 09:39:39 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_jg_address.position_code
     *
     * @mbggenerated Mon Aug 08 09:39:39 CST 2016
     */
    private String positionCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_jg_address.address_id
     *
     * @return the value of cms_jg_address.address_id
     *
     * @mbggenerated Mon Aug 08 09:39:39 CST 2016
     */
    public Double getProvinceCode() {
        return provinceCode;
    }

    public String getAddressId() {
		return addressId;
	}

	public void setAddressId(String addressId) {
		this.addressId = addressId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_jg_address.province_code
     *
     * @param provinceCode the value for cms_jg_address.province_code
     *
     * @mbggenerated Mon Aug 08 09:39:39 CST 2016
     */
    public void setProvinceCode(Double provinceCode) {
        this.provinceCode = provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_jg_address.province
     *
     * @return the value of cms_jg_address.province
     *
     * @mbggenerated Mon Aug 08 09:39:39 CST 2016
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_jg_address.province
     *
     * @param province the value for cms_jg_address.province
     *
     * @mbggenerated Mon Aug 08 09:39:39 CST 2016
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_jg_address.city_code
     *
     * @return the value of cms_jg_address.city_code
     *
     * @mbggenerated Mon Aug 08 09:39:39 CST 2016
     */
    public Double getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_jg_address.city_code
     *
     * @param cityCode the value for cms_jg_address.city_code
     *
     * @mbggenerated Mon Aug 08 09:39:39 CST 2016
     */
    public void setCityCode(Double cityCode) {
        this.cityCode = cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_jg_address.city
     *
     * @return the value of cms_jg_address.city
     *
     * @mbggenerated Mon Aug 08 09:39:39 CST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_jg_address.city
     *
     * @param city the value for cms_jg_address.city
     *
     * @mbggenerated Mon Aug 08 09:39:39 CST 2016
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_jg_address.county_code
     *
     * @return the value of cms_jg_address.county_code
     *
     * @mbggenerated Mon Aug 08 09:39:39 CST 2016
     */
    public Double getCountyCode() {
        return countyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_jg_address.county_code
     *
     * @param countyCode the value for cms_jg_address.county_code
     *
     * @mbggenerated Mon Aug 08 09:39:39 CST 2016
     */
    public void setCountyCode(Double countyCode) {
        this.countyCode = countyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_jg_address.county
     *
     * @return the value of cms_jg_address.county
     *
     * @mbggenerated Mon Aug 08 09:39:39 CST 2016
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_jg_address.county
     *
     * @param county the value for cms_jg_address.county
     *
     * @mbggenerated Mon Aug 08 09:39:39 CST 2016
     */
    public void setCounty(String county) {
        this.county = county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_jg_address.road_code
     *
     * @return the value of cms_jg_address.road_code
     *
     * @mbggenerated Mon Aug 08 09:39:39 CST 2016
     */
    public Double getRoadCode() {
        return roadCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_jg_address.road_code
     *
     * @param roadCode the value for cms_jg_address.road_code
     *
     * @mbggenerated Mon Aug 08 09:39:39 CST 2016
     */
    public void setRoadCode(Double roadCode) {
        this.roadCode = roadCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_jg_address.road
     *
     * @return the value of cms_jg_address.road
     *
     * @mbggenerated Mon Aug 08 09:39:39 CST 2016
     */
    public String getRoad() {
        return road;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_jg_address.road
     *
     * @param road the value for cms_jg_address.road
     *
     * @mbggenerated Mon Aug 08 09:39:39 CST 2016
     */
    public void setRoad(String road) {
        this.road = road;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_jg_address.address
     *
     * @return the value of cms_jg_address.address
     *
     * @mbggenerated Mon Aug 08 09:39:39 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_jg_address.address
     *
     * @param address the value for cms_jg_address.address
     *
     * @mbggenerated Mon Aug 08 09:39:39 CST 2016
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_jg_address.position_code
     *
     * @return the value of cms_jg_address.position_code
     *
     * @mbggenerated Mon Aug 08 09:39:39 CST 2016
     */
    public String getPositionCode() {
        return positionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_jg_address.position_code
     *
     * @param positionCode the value for cms_jg_address.position_code
     *
     * @mbggenerated Mon Aug 08 09:39:39 CST 2016
     */
    public void setPositionCode(String positionCode) {
        this.positionCode = positionCode;
    }
}