package com.huatuo.clinics.cms.db.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CsOutpEmrExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cs_outp_emr
     *
     * @mbggenerated Mon Jul 11 17:57:07 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cs_outp_emr
     *
     * @mbggenerated Mon Jul 11 17:57:07 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cs_outp_emr
     *
     * @mbggenerated Mon Jul 11 17:57:07 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_outp_emr
     *
     * @mbggenerated Mon Jul 11 17:57:07 CST 2016
     */
    public CsOutpEmrExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_outp_emr
     *
     * @mbggenerated Mon Jul 11 17:57:07 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_outp_emr
     *
     * @mbggenerated Mon Jul 11 17:57:07 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_outp_emr
     *
     * @mbggenerated Mon Jul 11 17:57:07 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_outp_emr
     *
     * @mbggenerated Mon Jul 11 17:57:07 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_outp_emr
     *
     * @mbggenerated Mon Jul 11 17:57:07 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_outp_emr
     *
     * @mbggenerated Mon Jul 11 17:57:07 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_outp_emr
     *
     * @mbggenerated Mon Jul 11 17:57:07 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_outp_emr
     *
     * @mbggenerated Mon Jul 11 17:57:07 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_outp_emr
     *
     * @mbggenerated Mon Jul 11 17:57:07 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_outp_emr
     *
     * @mbggenerated Mon Jul 11 17:57:07 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cs_outp_emr
     *
     * @mbggenerated Mon Jul 11 17:57:07 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andVisitIdIsNull() {
            addCriterion("visit_id is null");
            return (Criteria) this;
        }

        public Criteria andVisitIdIsNotNull() {
            addCriterion("visit_id is not null");
            return (Criteria) this;
        }

        public Criteria andVisitIdEqualTo(String value) {
            addCriterion("visit_id =", value, "visitId");
            return (Criteria) this;
        }

        public Criteria andVisitIdNotEqualTo(String value) {
            addCriterion("visit_id <>", value, "visitId");
            return (Criteria) this;
        }

        public Criteria andVisitIdGreaterThan(String value) {
            addCriterion("visit_id >", value, "visitId");
            return (Criteria) this;
        }

        public Criteria andVisitIdGreaterThanOrEqualTo(String value) {
            addCriterion("visit_id >=", value, "visitId");
            return (Criteria) this;
        }

        public Criteria andVisitIdLessThan(String value) {
            addCriterion("visit_id <", value, "visitId");
            return (Criteria) this;
        }

        public Criteria andVisitIdLessThanOrEqualTo(String value) {
            addCriterion("visit_id <=", value, "visitId");
            return (Criteria) this;
        }

        public Criteria andVisitIdLike(String value) {
            addCriterion("visit_id like", value, "visitId");
            return (Criteria) this;
        }

        public Criteria andVisitIdNotLike(String value) {
            addCriterion("visit_id not like", value, "visitId");
            return (Criteria) this;
        }

        public Criteria andVisitIdIn(List<String> values) {
            addCriterion("visit_id in", values, "visitId");
            return (Criteria) this;
        }

        public Criteria andVisitIdNotIn(List<String> values) {
            addCriterion("visit_id not in", values, "visitId");
            return (Criteria) this;
        }

        public Criteria andVisitIdBetween(String value1, String value2) {
            addCriterion("visit_id between", value1, value2, "visitId");
            return (Criteria) this;
        }

        public Criteria andVisitIdNotBetween(String value1, String value2) {
            addCriterion("visit_id not between", value1, value2, "visitId");
            return (Criteria) this;
        }

        public Criteria andPatientIdIsNull() {
            addCriterion("patient_id is null");
            return (Criteria) this;
        }

        public Criteria andPatientIdIsNotNull() {
            addCriterion("patient_id is not null");
            return (Criteria) this;
        }

        public Criteria andPatientIdEqualTo(String value) {
            addCriterion("patient_id =", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdNotEqualTo(String value) {
            addCriterion("patient_id <>", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdGreaterThan(String value) {
            addCriterion("patient_id >", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdGreaterThanOrEqualTo(String value) {
            addCriterion("patient_id >=", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdLessThan(String value) {
            addCriterion("patient_id <", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdLessThanOrEqualTo(String value) {
            addCriterion("patient_id <=", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdLike(String value) {
            addCriterion("patient_id like", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdNotLike(String value) {
            addCriterion("patient_id not like", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdIn(List<String> values) {
            addCriterion("patient_id in", values, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdNotIn(List<String> values) {
            addCriterion("patient_id not in", values, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdBetween(String value1, String value2) {
            addCriterion("patient_id between", value1, value2, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdNotBetween(String value1, String value2) {
            addCriterion("patient_id not between", value1, value2, "patientId");
            return (Criteria) this;
        }

        public Criteria andTimesIsNull() {
            addCriterion("times is null");
            return (Criteria) this;
        }

        public Criteria andTimesIsNotNull() {
            addCriterion("times is not null");
            return (Criteria) this;
        }

        public Criteria andTimesEqualTo(Integer value) {
            addCriterion("times =", value, "times");
            return (Criteria) this;
        }

        public Criteria andTimesNotEqualTo(Integer value) {
            addCriterion("times <>", value, "times");
            return (Criteria) this;
        }

        public Criteria andTimesGreaterThan(Integer value) {
            addCriterion("times >", value, "times");
            return (Criteria) this;
        }

        public Criteria andTimesGreaterThanOrEqualTo(Integer value) {
            addCriterion("times >=", value, "times");
            return (Criteria) this;
        }

        public Criteria andTimesLessThan(Integer value) {
            addCriterion("times <", value, "times");
            return (Criteria) this;
        }

        public Criteria andTimesLessThanOrEqualTo(Integer value) {
            addCriterion("times <=", value, "times");
            return (Criteria) this;
        }

        public Criteria andTimesIn(List<Integer> values) {
            addCriterion("times in", values, "times");
            return (Criteria) this;
        }

        public Criteria andTimesNotIn(List<Integer> values) {
            addCriterion("times not in", values, "times");
            return (Criteria) this;
        }

        public Criteria andTimesBetween(Integer value1, Integer value2) {
            addCriterion("times between", value1, value2, "times");
            return (Criteria) this;
        }

        public Criteria andTimesNotBetween(Integer value1, Integer value2) {
            addCriterion("times not between", value1, value2, "times");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andAgeIsNull() {
            addCriterion("age is null");
            return (Criteria) this;
        }

        public Criteria andAgeIsNotNull() {
            addCriterion("age is not null");
            return (Criteria) this;
        }

        public Criteria andAgeEqualTo(String value) {
            addCriterion("age =", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotEqualTo(String value) {
            addCriterion("age <>", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThan(String value) {
            addCriterion("age >", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThanOrEqualTo(String value) {
            addCriterion("age >=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThan(String value) {
            addCriterion("age <", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThanOrEqualTo(String value) {
            addCriterion("age <=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLike(String value) {
            addCriterion("age like", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotLike(String value) {
            addCriterion("age not like", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeIn(List<String> values) {
            addCriterion("age in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotIn(List<String> values) {
            addCriterion("age not in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeBetween(String value1, String value2) {
            addCriterion("age between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotBetween(String value1, String value2) {
            addCriterion("age not between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("sex is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("sex is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(String value) {
            addCriterion("sex =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(String value) {
            addCriterion("sex <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(String value) {
            addCriterion("sex >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(String value) {
            addCriterion("sex >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(String value) {
            addCriterion("sex <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(String value) {
            addCriterion("sex <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLike(String value) {
            addCriterion("sex like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotLike(String value) {
            addCriterion("sex not like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<String> values) {
            addCriterion("sex in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<String> values) {
            addCriterion("sex not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(String value1, String value2) {
            addCriterion("sex between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(String value1, String value2) {
            addCriterion("sex not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andMarryIsNull() {
            addCriterion("marry is null");
            return (Criteria) this;
        }

        public Criteria andMarryIsNotNull() {
            addCriterion("marry is not null");
            return (Criteria) this;
        }

        public Criteria andMarryEqualTo(String value) {
            addCriterion("marry =", value, "marry");
            return (Criteria) this;
        }

        public Criteria andMarryNotEqualTo(String value) {
            addCriterion("marry <>", value, "marry");
            return (Criteria) this;
        }

        public Criteria andMarryGreaterThan(String value) {
            addCriterion("marry >", value, "marry");
            return (Criteria) this;
        }

        public Criteria andMarryGreaterThanOrEqualTo(String value) {
            addCriterion("marry >=", value, "marry");
            return (Criteria) this;
        }

        public Criteria andMarryLessThan(String value) {
            addCriterion("marry <", value, "marry");
            return (Criteria) this;
        }

        public Criteria andMarryLessThanOrEqualTo(String value) {
            addCriterion("marry <=", value, "marry");
            return (Criteria) this;
        }

        public Criteria andMarryLike(String value) {
            addCriterion("marry like", value, "marry");
            return (Criteria) this;
        }

        public Criteria andMarryNotLike(String value) {
            addCriterion("marry not like", value, "marry");
            return (Criteria) this;
        }

        public Criteria andMarryIn(List<String> values) {
            addCriterion("marry in", values, "marry");
            return (Criteria) this;
        }

        public Criteria andMarryNotIn(List<String> values) {
            addCriterion("marry not in", values, "marry");
            return (Criteria) this;
        }

        public Criteria andMarryBetween(String value1, String value2) {
            addCriterion("marry between", value1, value2, "marry");
            return (Criteria) this;
        }

        public Criteria andMarryNotBetween(String value1, String value2) {
            addCriterion("marry not between", value1, value2, "marry");
            return (Criteria) this;
        }

        public Criteria andBirthPlaceIsNull() {
            addCriterion("birth_place is null");
            return (Criteria) this;
        }

        public Criteria andBirthPlaceIsNotNull() {
            addCriterion("birth_place is not null");
            return (Criteria) this;
        }

        public Criteria andBirthPlaceEqualTo(String value) {
            addCriterion("birth_place =", value, "birthPlace");
            return (Criteria) this;
        }

        public Criteria andBirthPlaceNotEqualTo(String value) {
            addCriterion("birth_place <>", value, "birthPlace");
            return (Criteria) this;
        }

        public Criteria andBirthPlaceGreaterThan(String value) {
            addCriterion("birth_place >", value, "birthPlace");
            return (Criteria) this;
        }

        public Criteria andBirthPlaceGreaterThanOrEqualTo(String value) {
            addCriterion("birth_place >=", value, "birthPlace");
            return (Criteria) this;
        }

        public Criteria andBirthPlaceLessThan(String value) {
            addCriterion("birth_place <", value, "birthPlace");
            return (Criteria) this;
        }

        public Criteria andBirthPlaceLessThanOrEqualTo(String value) {
            addCriterion("birth_place <=", value, "birthPlace");
            return (Criteria) this;
        }

        public Criteria andBirthPlaceLike(String value) {
            addCriterion("birth_place like", value, "birthPlace");
            return (Criteria) this;
        }

        public Criteria andBirthPlaceNotLike(String value) {
            addCriterion("birth_place not like", value, "birthPlace");
            return (Criteria) this;
        }

        public Criteria andBirthPlaceIn(List<String> values) {
            addCriterion("birth_place in", values, "birthPlace");
            return (Criteria) this;
        }

        public Criteria andBirthPlaceNotIn(List<String> values) {
            addCriterion("birth_place not in", values, "birthPlace");
            return (Criteria) this;
        }

        public Criteria andBirthPlaceBetween(String value1, String value2) {
            addCriterion("birth_place between", value1, value2, "birthPlace");
            return (Criteria) this;
        }

        public Criteria andBirthPlaceNotBetween(String value1, String value2) {
            addCriterion("birth_place not between", value1, value2, "birthPlace");
            return (Criteria) this;
        }

        public Criteria andAddressIdIsNull() {
            addCriterion("address_id is null");
            return (Criteria) this;
        }

        public Criteria andAddressIdIsNotNull() {
            addCriterion("address_id is not null");
            return (Criteria) this;
        }

        public Criteria andAddressIdEqualTo(Long value) {
            addCriterion("address_id =", value, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdNotEqualTo(Long value) {
            addCriterion("address_id <>", value, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdGreaterThan(Long value) {
            addCriterion("address_id >", value, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdGreaterThanOrEqualTo(Long value) {
            addCriterion("address_id >=", value, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdLessThan(Long value) {
            addCriterion("address_id <", value, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdLessThanOrEqualTo(Long value) {
            addCriterion("address_id <=", value, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdIn(List<Long> values) {
            addCriterion("address_id in", values, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdNotIn(List<Long> values) {
            addCriterion("address_id not in", values, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdBetween(Long value1, Long value2) {
            addCriterion("address_id between", value1, value2, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdNotBetween(Long value1, Long value2) {
            addCriterion("address_id not between", value1, value2, "addressId");
            return (Criteria) this;
        }

        public Criteria andOccupationIdIsNull() {
            addCriterion("occupation_id is null");
            return (Criteria) this;
        }

        public Criteria andOccupationIdIsNotNull() {
            addCriterion("occupation_id is not null");
            return (Criteria) this;
        }

        public Criteria andOccupationIdEqualTo(String value) {
            addCriterion("occupation_id =", value, "occupationId");
            return (Criteria) this;
        }

        public Criteria andOccupationIdNotEqualTo(String value) {
            addCriterion("occupation_id <>", value, "occupationId");
            return (Criteria) this;
        }

        public Criteria andOccupationIdGreaterThan(String value) {
            addCriterion("occupation_id >", value, "occupationId");
            return (Criteria) this;
        }

        public Criteria andOccupationIdGreaterThanOrEqualTo(String value) {
            addCriterion("occupation_id >=", value, "occupationId");
            return (Criteria) this;
        }

        public Criteria andOccupationIdLessThan(String value) {
            addCriterion("occupation_id <", value, "occupationId");
            return (Criteria) this;
        }

        public Criteria andOccupationIdLessThanOrEqualTo(String value) {
            addCriterion("occupation_id <=", value, "occupationId");
            return (Criteria) this;
        }

        public Criteria andOccupationIdLike(String value) {
            addCriterion("occupation_id like", value, "occupationId");
            return (Criteria) this;
        }

        public Criteria andOccupationIdNotLike(String value) {
            addCriterion("occupation_id not like", value, "occupationId");
            return (Criteria) this;
        }

        public Criteria andOccupationIdIn(List<String> values) {
            addCriterion("occupation_id in", values, "occupationId");
            return (Criteria) this;
        }

        public Criteria andOccupationIdNotIn(List<String> values) {
            addCriterion("occupation_id not in", values, "occupationId");
            return (Criteria) this;
        }

        public Criteria andOccupationIdBetween(String value1, String value2) {
            addCriterion("occupation_id between", value1, value2, "occupationId");
            return (Criteria) this;
        }

        public Criteria andOccupationIdNotBetween(String value1, String value2) {
            addCriterion("occupation_id not between", value1, value2, "occupationId");
            return (Criteria) this;
        }

        public Criteria andRelateTelIsNull() {
            addCriterion("relate_tel is null");
            return (Criteria) this;
        }

        public Criteria andRelateTelIsNotNull() {
            addCriterion("relate_tel is not null");
            return (Criteria) this;
        }

        public Criteria andRelateTelEqualTo(String value) {
            addCriterion("relate_tel =", value, "relateTel");
            return (Criteria) this;
        }

        public Criteria andRelateTelNotEqualTo(String value) {
            addCriterion("relate_tel <>", value, "relateTel");
            return (Criteria) this;
        }

        public Criteria andRelateTelGreaterThan(String value) {
            addCriterion("relate_tel >", value, "relateTel");
            return (Criteria) this;
        }

        public Criteria andRelateTelGreaterThanOrEqualTo(String value) {
            addCriterion("relate_tel >=", value, "relateTel");
            return (Criteria) this;
        }

        public Criteria andRelateTelLessThan(String value) {
            addCriterion("relate_tel <", value, "relateTel");
            return (Criteria) this;
        }

        public Criteria andRelateTelLessThanOrEqualTo(String value) {
            addCriterion("relate_tel <=", value, "relateTel");
            return (Criteria) this;
        }

        public Criteria andRelateTelLike(String value) {
            addCriterion("relate_tel like", value, "relateTel");
            return (Criteria) this;
        }

        public Criteria andRelateTelNotLike(String value) {
            addCriterion("relate_tel not like", value, "relateTel");
            return (Criteria) this;
        }

        public Criteria andRelateTelIn(List<String> values) {
            addCriterion("relate_tel in", values, "relateTel");
            return (Criteria) this;
        }

        public Criteria andRelateTelNotIn(List<String> values) {
            addCriterion("relate_tel not in", values, "relateTel");
            return (Criteria) this;
        }

        public Criteria andRelateTelBetween(String value1, String value2) {
            addCriterion("relate_tel between", value1, value2, "relateTel");
            return (Criteria) this;
        }

        public Criteria andRelateTelNotBetween(String value1, String value2) {
            addCriterion("relate_tel not between", value1, value2, "relateTel");
            return (Criteria) this;
        }

        public Criteria andSocialIdTypeIsNull() {
            addCriterion("social_id_type is null");
            return (Criteria) this;
        }

        public Criteria andSocialIdTypeIsNotNull() {
            addCriterion("social_id_type is not null");
            return (Criteria) this;
        }

        public Criteria andSocialIdTypeEqualTo(Integer value) {
            addCriterion("social_id_type =", value, "socialIdType");
            return (Criteria) this;
        }

        public Criteria andSocialIdTypeNotEqualTo(Integer value) {
            addCriterion("social_id_type <>", value, "socialIdType");
            return (Criteria) this;
        }

        public Criteria andSocialIdTypeGreaterThan(Integer value) {
            addCriterion("social_id_type >", value, "socialIdType");
            return (Criteria) this;
        }

        public Criteria andSocialIdTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("social_id_type >=", value, "socialIdType");
            return (Criteria) this;
        }

        public Criteria andSocialIdTypeLessThan(Integer value) {
            addCriterion("social_id_type <", value, "socialIdType");
            return (Criteria) this;
        }

        public Criteria andSocialIdTypeLessThanOrEqualTo(Integer value) {
            addCriterion("social_id_type <=", value, "socialIdType");
            return (Criteria) this;
        }

        public Criteria andSocialIdTypeIn(List<Integer> values) {
            addCriterion("social_id_type in", values, "socialIdType");
            return (Criteria) this;
        }

        public Criteria andSocialIdTypeNotIn(List<Integer> values) {
            addCriterion("social_id_type not in", values, "socialIdType");
            return (Criteria) this;
        }

        public Criteria andSocialIdTypeBetween(Integer value1, Integer value2) {
            addCriterion("social_id_type between", value1, value2, "socialIdType");
            return (Criteria) this;
        }

        public Criteria andSocialIdTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("social_id_type not between", value1, value2, "socialIdType");
            return (Criteria) this;
        }

        public Criteria andSocialIdIsNull() {
            addCriterion("social_id is null");
            return (Criteria) this;
        }

        public Criteria andSocialIdIsNotNull() {
            addCriterion("social_id is not null");
            return (Criteria) this;
        }

        public Criteria andSocialIdEqualTo(String value) {
            addCriterion("social_id =", value, "socialId");
            return (Criteria) this;
        }

        public Criteria andSocialIdNotEqualTo(String value) {
            addCriterion("social_id <>", value, "socialId");
            return (Criteria) this;
        }

        public Criteria andSocialIdGreaterThan(String value) {
            addCriterion("social_id >", value, "socialId");
            return (Criteria) this;
        }

        public Criteria andSocialIdGreaterThanOrEqualTo(String value) {
            addCriterion("social_id >=", value, "socialId");
            return (Criteria) this;
        }

        public Criteria andSocialIdLessThan(String value) {
            addCriterion("social_id <", value, "socialId");
            return (Criteria) this;
        }

        public Criteria andSocialIdLessThanOrEqualTo(String value) {
            addCriterion("social_id <=", value, "socialId");
            return (Criteria) this;
        }

        public Criteria andSocialIdLike(String value) {
            addCriterion("social_id like", value, "socialId");
            return (Criteria) this;
        }

        public Criteria andSocialIdNotLike(String value) {
            addCriterion("social_id not like", value, "socialId");
            return (Criteria) this;
        }

        public Criteria andSocialIdIn(List<String> values) {
            addCriterion("social_id in", values, "socialId");
            return (Criteria) this;
        }

        public Criteria andSocialIdNotIn(List<String> values) {
            addCriterion("social_id not in", values, "socialId");
            return (Criteria) this;
        }

        public Criteria andSocialIdBetween(String value1, String value2) {
            addCriterion("social_id between", value1, value2, "socialId");
            return (Criteria) this;
        }

        public Criteria andSocialIdNotBetween(String value1, String value2) {
            addCriterion("social_id not between", value1, value2, "socialId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateDoctorIsNull() {
            addCriterion("create_doctor is null");
            return (Criteria) this;
        }

        public Criteria andCreateDoctorIsNotNull() {
            addCriterion("create_doctor is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDoctorEqualTo(String value) {
            addCriterion("create_doctor =", value, "createDoctor");
            return (Criteria) this;
        }

        public Criteria andCreateDoctorNotEqualTo(String value) {
            addCriterion("create_doctor <>", value, "createDoctor");
            return (Criteria) this;
        }

        public Criteria andCreateDoctorGreaterThan(String value) {
            addCriterion("create_doctor >", value, "createDoctor");
            return (Criteria) this;
        }

        public Criteria andCreateDoctorGreaterThanOrEqualTo(String value) {
            addCriterion("create_doctor >=", value, "createDoctor");
            return (Criteria) this;
        }

        public Criteria andCreateDoctorLessThan(String value) {
            addCriterion("create_doctor <", value, "createDoctor");
            return (Criteria) this;
        }

        public Criteria andCreateDoctorLessThanOrEqualTo(String value) {
            addCriterion("create_doctor <=", value, "createDoctor");
            return (Criteria) this;
        }

        public Criteria andCreateDoctorLike(String value) {
            addCriterion("create_doctor like", value, "createDoctor");
            return (Criteria) this;
        }

        public Criteria andCreateDoctorNotLike(String value) {
            addCriterion("create_doctor not like", value, "createDoctor");
            return (Criteria) this;
        }

        public Criteria andCreateDoctorIn(List<String> values) {
            addCriterion("create_doctor in", values, "createDoctor");
            return (Criteria) this;
        }

        public Criteria andCreateDoctorNotIn(List<String> values) {
            addCriterion("create_doctor not in", values, "createDoctor");
            return (Criteria) this;
        }

        public Criteria andCreateDoctorBetween(String value1, String value2) {
            addCriterion("create_doctor between", value1, value2, "createDoctor");
            return (Criteria) this;
        }

        public Criteria andCreateDoctorNotBetween(String value1, String value2) {
            addCriterion("create_doctor not between", value1, value2, "createDoctor");
            return (Criteria) this;
        }

        public Criteria andChiefComplaintIsNull() {
            addCriterion("chief_complaint is null");
            return (Criteria) this;
        }

        public Criteria andChiefComplaintIsNotNull() {
            addCriterion("chief_complaint is not null");
            return (Criteria) this;
        }

        public Criteria andChiefComplaintEqualTo(String value) {
            addCriterion("chief_complaint =", value, "chiefComplaint");
            return (Criteria) this;
        }

        public Criteria andChiefComplaintNotEqualTo(String value) {
            addCriterion("chief_complaint <>", value, "chiefComplaint");
            return (Criteria) this;
        }

        public Criteria andChiefComplaintGreaterThan(String value) {
            addCriterion("chief_complaint >", value, "chiefComplaint");
            return (Criteria) this;
        }

        public Criteria andChiefComplaintGreaterThanOrEqualTo(String value) {
            addCriterion("chief_complaint >=", value, "chiefComplaint");
            return (Criteria) this;
        }

        public Criteria andChiefComplaintLessThan(String value) {
            addCriterion("chief_complaint <", value, "chiefComplaint");
            return (Criteria) this;
        }

        public Criteria andChiefComplaintLessThanOrEqualTo(String value) {
            addCriterion("chief_complaint <=", value, "chiefComplaint");
            return (Criteria) this;
        }

        public Criteria andChiefComplaintLike(String value) {
            addCriterion("chief_complaint like", value, "chiefComplaint");
            return (Criteria) this;
        }

        public Criteria andChiefComplaintNotLike(String value) {
            addCriterion("chief_complaint not like", value, "chiefComplaint");
            return (Criteria) this;
        }

        public Criteria andChiefComplaintIn(List<String> values) {
            addCriterion("chief_complaint in", values, "chiefComplaint");
            return (Criteria) this;
        }

        public Criteria andChiefComplaintNotIn(List<String> values) {
            addCriterion("chief_complaint not in", values, "chiefComplaint");
            return (Criteria) this;
        }

        public Criteria andChiefComplaintBetween(String value1, String value2) {
            addCriterion("chief_complaint between", value1, value2, "chiefComplaint");
            return (Criteria) this;
        }

        public Criteria andChiefComplaintNotBetween(String value1, String value2) {
            addCriterion("chief_complaint not between", value1, value2, "chiefComplaint");
            return (Criteria) this;
        }

        public Criteria andAllergicHistoryIsNull() {
            addCriterion("allergic_history is null");
            return (Criteria) this;
        }

        public Criteria andAllergicHistoryIsNotNull() {
            addCriterion("allergic_history is not null");
            return (Criteria) this;
        }

        public Criteria andAllergicHistoryEqualTo(String value) {
            addCriterion("allergic_history =", value, "allergicHistory");
            return (Criteria) this;
        }

        public Criteria andAllergicHistoryNotEqualTo(String value) {
            addCriterion("allergic_history <>", value, "allergicHistory");
            return (Criteria) this;
        }

        public Criteria andAllergicHistoryGreaterThan(String value) {
            addCriterion("allergic_history >", value, "allergicHistory");
            return (Criteria) this;
        }

        public Criteria andAllergicHistoryGreaterThanOrEqualTo(String value) {
            addCriterion("allergic_history >=", value, "allergicHistory");
            return (Criteria) this;
        }

        public Criteria andAllergicHistoryLessThan(String value) {
            addCriterion("allergic_history <", value, "allergicHistory");
            return (Criteria) this;
        }

        public Criteria andAllergicHistoryLessThanOrEqualTo(String value) {
            addCriterion("allergic_history <=", value, "allergicHistory");
            return (Criteria) this;
        }

        public Criteria andAllergicHistoryLike(String value) {
            addCriterion("allergic_history like", value, "allergicHistory");
            return (Criteria) this;
        }

        public Criteria andAllergicHistoryNotLike(String value) {
            addCriterion("allergic_history not like", value, "allergicHistory");
            return (Criteria) this;
        }

        public Criteria andAllergicHistoryIn(List<String> values) {
            addCriterion("allergic_history in", values, "allergicHistory");
            return (Criteria) this;
        }

        public Criteria andAllergicHistoryNotIn(List<String> values) {
            addCriterion("allergic_history not in", values, "allergicHistory");
            return (Criteria) this;
        }

        public Criteria andAllergicHistoryBetween(String value1, String value2) {
            addCriterion("allergic_history between", value1, value2, "allergicHistory");
            return (Criteria) this;
        }

        public Criteria andAllergicHistoryNotBetween(String value1, String value2) {
            addCriterion("allergic_history not between", value1, value2, "allergicHistory");
            return (Criteria) this;
        }

        public Criteria andPresentIllnessIsNull() {
            addCriterion("present_illness is null");
            return (Criteria) this;
        }

        public Criteria andPresentIllnessIsNotNull() {
            addCriterion("present_illness is not null");
            return (Criteria) this;
        }

        public Criteria andPresentIllnessEqualTo(String value) {
            addCriterion("present_illness =", value, "presentIllness");
            return (Criteria) this;
        }

        public Criteria andPresentIllnessNotEqualTo(String value) {
            addCriterion("present_illness <>", value, "presentIllness");
            return (Criteria) this;
        }

        public Criteria andPresentIllnessGreaterThan(String value) {
            addCriterion("present_illness >", value, "presentIllness");
            return (Criteria) this;
        }

        public Criteria andPresentIllnessGreaterThanOrEqualTo(String value) {
            addCriterion("present_illness >=", value, "presentIllness");
            return (Criteria) this;
        }

        public Criteria andPresentIllnessLessThan(String value) {
            addCriterion("present_illness <", value, "presentIllness");
            return (Criteria) this;
        }

        public Criteria andPresentIllnessLessThanOrEqualTo(String value) {
            addCriterion("present_illness <=", value, "presentIllness");
            return (Criteria) this;
        }

        public Criteria andPresentIllnessLike(String value) {
            addCriterion("present_illness like", value, "presentIllness");
            return (Criteria) this;
        }

        public Criteria andPresentIllnessNotLike(String value) {
            addCriterion("present_illness not like", value, "presentIllness");
            return (Criteria) this;
        }

        public Criteria andPresentIllnessIn(List<String> values) {
            addCriterion("present_illness in", values, "presentIllness");
            return (Criteria) this;
        }

        public Criteria andPresentIllnessNotIn(List<String> values) {
            addCriterion("present_illness not in", values, "presentIllness");
            return (Criteria) this;
        }

        public Criteria andPresentIllnessBetween(String value1, String value2) {
            addCriterion("present_illness between", value1, value2, "presentIllness");
            return (Criteria) this;
        }

        public Criteria andPresentIllnessNotBetween(String value1, String value2) {
            addCriterion("present_illness not between", value1, value2, "presentIllness");
            return (Criteria) this;
        }

        public Criteria andPastIllnessIsNull() {
            addCriterion("past_illness is null");
            return (Criteria) this;
        }

        public Criteria andPastIllnessIsNotNull() {
            addCriterion("past_illness is not null");
            return (Criteria) this;
        }

        public Criteria andPastIllnessEqualTo(String value) {
            addCriterion("past_illness =", value, "pastIllness");
            return (Criteria) this;
        }

        public Criteria andPastIllnessNotEqualTo(String value) {
            addCriterion("past_illness <>", value, "pastIllness");
            return (Criteria) this;
        }

        public Criteria andPastIllnessGreaterThan(String value) {
            addCriterion("past_illness >", value, "pastIllness");
            return (Criteria) this;
        }

        public Criteria andPastIllnessGreaterThanOrEqualTo(String value) {
            addCriterion("past_illness >=", value, "pastIllness");
            return (Criteria) this;
        }

        public Criteria andPastIllnessLessThan(String value) {
            addCriterion("past_illness <", value, "pastIllness");
            return (Criteria) this;
        }

        public Criteria andPastIllnessLessThanOrEqualTo(String value) {
            addCriterion("past_illness <=", value, "pastIllness");
            return (Criteria) this;
        }

        public Criteria andPastIllnessLike(String value) {
            addCriterion("past_illness like", value, "pastIllness");
            return (Criteria) this;
        }

        public Criteria andPastIllnessNotLike(String value) {
            addCriterion("past_illness not like", value, "pastIllness");
            return (Criteria) this;
        }

        public Criteria andPastIllnessIn(List<String> values) {
            addCriterion("past_illness in", values, "pastIllness");
            return (Criteria) this;
        }

        public Criteria andPastIllnessNotIn(List<String> values) {
            addCriterion("past_illness not in", values, "pastIllness");
            return (Criteria) this;
        }

        public Criteria andPastIllnessBetween(String value1, String value2) {
            addCriterion("past_illness between", value1, value2, "pastIllness");
            return (Criteria) this;
        }

        public Criteria andPastIllnessNotBetween(String value1, String value2) {
            addCriterion("past_illness not between", value1, value2, "pastIllness");
            return (Criteria) this;
        }

        public Criteria andPersonalIllnessIsNull() {
            addCriterion("personal_illness is null");
            return (Criteria) this;
        }

        public Criteria andPersonalIllnessIsNotNull() {
            addCriterion("personal_illness is not null");
            return (Criteria) this;
        }

        public Criteria andPersonalIllnessEqualTo(String value) {
            addCriterion("personal_illness =", value, "personalIllness");
            return (Criteria) this;
        }

        public Criteria andPersonalIllnessNotEqualTo(String value) {
            addCriterion("personal_illness <>", value, "personalIllness");
            return (Criteria) this;
        }

        public Criteria andPersonalIllnessGreaterThan(String value) {
            addCriterion("personal_illness >", value, "personalIllness");
            return (Criteria) this;
        }

        public Criteria andPersonalIllnessGreaterThanOrEqualTo(String value) {
            addCriterion("personal_illness >=", value, "personalIllness");
            return (Criteria) this;
        }

        public Criteria andPersonalIllnessLessThan(String value) {
            addCriterion("personal_illness <", value, "personalIllness");
            return (Criteria) this;
        }

        public Criteria andPersonalIllnessLessThanOrEqualTo(String value) {
            addCriterion("personal_illness <=", value, "personalIllness");
            return (Criteria) this;
        }

        public Criteria andPersonalIllnessLike(String value) {
            addCriterion("personal_illness like", value, "personalIllness");
            return (Criteria) this;
        }

        public Criteria andPersonalIllnessNotLike(String value) {
            addCriterion("personal_illness not like", value, "personalIllness");
            return (Criteria) this;
        }

        public Criteria andPersonalIllnessIn(List<String> values) {
            addCriterion("personal_illness in", values, "personalIllness");
            return (Criteria) this;
        }

        public Criteria andPersonalIllnessNotIn(List<String> values) {
            addCriterion("personal_illness not in", values, "personalIllness");
            return (Criteria) this;
        }

        public Criteria andPersonalIllnessBetween(String value1, String value2) {
            addCriterion("personal_illness between", value1, value2, "personalIllness");
            return (Criteria) this;
        }

        public Criteria andPersonalIllnessNotBetween(String value1, String value2) {
            addCriterion("personal_illness not between", value1, value2, "personalIllness");
            return (Criteria) this;
        }

        public Criteria andSuggestionIsNull() {
            addCriterion("suggestion is null");
            return (Criteria) this;
        }

        public Criteria andSuggestionIsNotNull() {
            addCriterion("suggestion is not null");
            return (Criteria) this;
        }

        public Criteria andSuggestionEqualTo(String value) {
            addCriterion("suggestion =", value, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionNotEqualTo(String value) {
            addCriterion("suggestion <>", value, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionGreaterThan(String value) {
            addCriterion("suggestion >", value, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionGreaterThanOrEqualTo(String value) {
            addCriterion("suggestion >=", value, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionLessThan(String value) {
            addCriterion("suggestion <", value, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionLessThanOrEqualTo(String value) {
            addCriterion("suggestion <=", value, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionLike(String value) {
            addCriterion("suggestion like", value, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionNotLike(String value) {
            addCriterion("suggestion not like", value, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionIn(List<String> values) {
            addCriterion("suggestion in", values, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionNotIn(List<String> values) {
            addCriterion("suggestion not in", values, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionBetween(String value1, String value2) {
            addCriterion("suggestion between", value1, value2, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionNotBetween(String value1, String value2) {
            addCriterion("suggestion not between", value1, value2, "suggestion");
            return (Criteria) this;
        }

        public Criteria andAuditDoctorIsNull() {
            addCriterion("audit_doctor is null");
            return (Criteria) this;
        }

        public Criteria andAuditDoctorIsNotNull() {
            addCriterion("audit_doctor is not null");
            return (Criteria) this;
        }

        public Criteria andAuditDoctorEqualTo(Long value) {
            addCriterion("audit_doctor =", value, "auditDoctor");
            return (Criteria) this;
        }

        public Criteria andAuditDoctorNotEqualTo(Long value) {
            addCriterion("audit_doctor <>", value, "auditDoctor");
            return (Criteria) this;
        }

        public Criteria andAuditDoctorGreaterThan(Long value) {
            addCriterion("audit_doctor >", value, "auditDoctor");
            return (Criteria) this;
        }

        public Criteria andAuditDoctorGreaterThanOrEqualTo(Long value) {
            addCriterion("audit_doctor >=", value, "auditDoctor");
            return (Criteria) this;
        }

        public Criteria andAuditDoctorLessThan(Long value) {
            addCriterion("audit_doctor <", value, "auditDoctor");
            return (Criteria) this;
        }

        public Criteria andAuditDoctorLessThanOrEqualTo(Long value) {
            addCriterion("audit_doctor <=", value, "auditDoctor");
            return (Criteria) this;
        }

        public Criteria andAuditDoctorIn(List<Long> values) {
            addCriterion("audit_doctor in", values, "auditDoctor");
            return (Criteria) this;
        }

        public Criteria andAuditDoctorNotIn(List<Long> values) {
            addCriterion("audit_doctor not in", values, "auditDoctor");
            return (Criteria) this;
        }

        public Criteria andAuditDoctorBetween(Long value1, Long value2) {
            addCriterion("audit_doctor between", value1, value2, "auditDoctor");
            return (Criteria) this;
        }

        public Criteria andAuditDoctorNotBetween(Long value1, Long value2) {
            addCriterion("audit_doctor not between", value1, value2, "auditDoctor");
            return (Criteria) this;
        }

        public Criteria andAuditTimeIsNull() {
            addCriterion("audit_time is null");
            return (Criteria) this;
        }

        public Criteria andAuditTimeIsNotNull() {
            addCriterion("audit_time is not null");
            return (Criteria) this;
        }

        public Criteria andAuditTimeEqualTo(String value) {
            addCriterion("audit_time =", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeNotEqualTo(String value) {
            addCriterion("audit_time <>", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeGreaterThan(String value) {
            addCriterion("audit_time >", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeGreaterThanOrEqualTo(String value) {
            addCriterion("audit_time >=", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeLessThan(String value) {
            addCriterion("audit_time <", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeLessThanOrEqualTo(String value) {
            addCriterion("audit_time <=", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeLike(String value) {
            addCriterion("audit_time like", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeNotLike(String value) {
            addCriterion("audit_time not like", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeIn(List<String> values) {
            addCriterion("audit_time in", values, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeNotIn(List<String> values) {
            addCriterion("audit_time not in", values, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeBetween(String value1, String value2) {
            addCriterion("audit_time between", value1, value2, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeNotBetween(String value1, String value2) {
            addCriterion("audit_time not between", value1, value2, "auditTime");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andBodyExamIsNull() {
            addCriterion("body_exam is null");
            return (Criteria) this;
        }

        public Criteria andBodyExamIsNotNull() {
            addCriterion("body_exam is not null");
            return (Criteria) this;
        }

        public Criteria andBodyExamEqualTo(String value) {
            addCriterion("body_exam =", value, "bodyExam");
            return (Criteria) this;
        }

        public Criteria andBodyExamNotEqualTo(String value) {
            addCriterion("body_exam <>", value, "bodyExam");
            return (Criteria) this;
        }

        public Criteria andBodyExamGreaterThan(String value) {
            addCriterion("body_exam >", value, "bodyExam");
            return (Criteria) this;
        }

        public Criteria andBodyExamGreaterThanOrEqualTo(String value) {
            addCriterion("body_exam >=", value, "bodyExam");
            return (Criteria) this;
        }

        public Criteria andBodyExamLessThan(String value) {
            addCriterion("body_exam <", value, "bodyExam");
            return (Criteria) this;
        }

        public Criteria andBodyExamLessThanOrEqualTo(String value) {
            addCriterion("body_exam <=", value, "bodyExam");
            return (Criteria) this;
        }

        public Criteria andBodyExamLike(String value) {
            addCriterion("body_exam like", value, "bodyExam");
            return (Criteria) this;
        }

        public Criteria andBodyExamNotLike(String value) {
            addCriterion("body_exam not like", value, "bodyExam");
            return (Criteria) this;
        }

        public Criteria andBodyExamIn(List<String> values) {
            addCriterion("body_exam in", values, "bodyExam");
            return (Criteria) this;
        }

        public Criteria andBodyExamNotIn(List<String> values) {
            addCriterion("body_exam not in", values, "bodyExam");
            return (Criteria) this;
        }

        public Criteria andBodyExamBetween(String value1, String value2) {
            addCriterion("body_exam between", value1, value2, "bodyExam");
            return (Criteria) this;
        }

        public Criteria andBodyExamNotBetween(String value1, String value2) {
            addCriterion("body_exam not between", value1, value2, "bodyExam");
            return (Criteria) this;
        }

        public Criteria andDiagnosesIsNull() {
            addCriterion("diagnoses is null");
            return (Criteria) this;
        }

        public Criteria andDiagnosesIsNotNull() {
            addCriterion("diagnoses is not null");
            return (Criteria) this;
        }

        public Criteria andDiagnosesEqualTo(String value) {
            addCriterion("diagnoses =", value, "diagnoses");
            return (Criteria) this;
        }

        public Criteria andDiagnosesNotEqualTo(String value) {
            addCriterion("diagnoses <>", value, "diagnoses");
            return (Criteria) this;
        }

        public Criteria andDiagnosesGreaterThan(String value) {
            addCriterion("diagnoses >", value, "diagnoses");
            return (Criteria) this;
        }

        public Criteria andDiagnosesGreaterThanOrEqualTo(String value) {
            addCriterion("diagnoses >=", value, "diagnoses");
            return (Criteria) this;
        }

        public Criteria andDiagnosesLessThan(String value) {
            addCriterion("diagnoses <", value, "diagnoses");
            return (Criteria) this;
        }

        public Criteria andDiagnosesLessThanOrEqualTo(String value) {
            addCriterion("diagnoses <=", value, "diagnoses");
            return (Criteria) this;
        }

        public Criteria andDiagnosesLike(String value) {
            addCriterion("diagnoses like", value, "diagnoses");
            return (Criteria) this;
        }

        public Criteria andDiagnosesNotLike(String value) {
            addCriterion("diagnoses not like", value, "diagnoses");
            return (Criteria) this;
        }

        public Criteria andDiagnosesIn(List<String> values) {
            addCriterion("diagnoses in", values, "diagnoses");
            return (Criteria) this;
        }

        public Criteria andDiagnosesNotIn(List<String> values) {
            addCriterion("diagnoses not in", values, "diagnoses");
            return (Criteria) this;
        }

        public Criteria andDiagnosesBetween(String value1, String value2) {
            addCriterion("diagnoses between", value1, value2, "diagnoses");
            return (Criteria) this;
        }

        public Criteria andDiagnosesNotBetween(String value1, String value2) {
            addCriterion("diagnoses not between", value1, value2, "diagnoses");
            return (Criteria) this;
        }

        public Criteria andHeightIsNull() {
            addCriterion("height is null");
            return (Criteria) this;
        }

        public Criteria andHeightIsNotNull() {
            addCriterion("height is not null");
            return (Criteria) this;
        }

        public Criteria andHeightEqualTo(Float value) {
            addCriterion("height =", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotEqualTo(Float value) {
            addCriterion("height <>", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThan(Float value) {
            addCriterion("height >", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThanOrEqualTo(Float value) {
            addCriterion("height >=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThan(Float value) {
            addCriterion("height <", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThanOrEqualTo(Float value) {
            addCriterion("height <=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightIn(List<Float> values) {
            addCriterion("height in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotIn(List<Float> values) {
            addCriterion("height not in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightBetween(Float value1, Float value2) {
            addCriterion("height between", value1, value2, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotBetween(Float value1, Float value2) {
            addCriterion("height not between", value1, value2, "height");
            return (Criteria) this;
        }

        public Criteria andWeightIsNull() {
            addCriterion("weight is null");
            return (Criteria) this;
        }

        public Criteria andWeightIsNotNull() {
            addCriterion("weight is not null");
            return (Criteria) this;
        }

        public Criteria andWeightEqualTo(Float value) {
            addCriterion("weight =", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotEqualTo(Float value) {
            addCriterion("weight <>", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThan(Float value) {
            addCriterion("weight >", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThanOrEqualTo(Float value) {
            addCriterion("weight >=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThan(Float value) {
            addCriterion("weight <", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThanOrEqualTo(Float value) {
            addCriterion("weight <=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightIn(List<Float> values) {
            addCriterion("weight in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotIn(List<Float> values) {
            addCriterion("weight not in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightBetween(Float value1, Float value2) {
            addCriterion("weight between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotBetween(Float value1, Float value2) {
            addCriterion("weight not between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andFamilyIllnessIsNull() {
            addCriterion("family_illness is null");
            return (Criteria) this;
        }

        public Criteria andFamilyIllnessIsNotNull() {
            addCriterion("family_illness is not null");
            return (Criteria) this;
        }

        public Criteria andFamilyIllnessEqualTo(String value) {
            addCriterion("family_illness =", value, "familyIllness");
            return (Criteria) this;
        }

        public Criteria andFamilyIllnessNotEqualTo(String value) {
            addCriterion("family_illness <>", value, "familyIllness");
            return (Criteria) this;
        }

        public Criteria andFamilyIllnessGreaterThan(String value) {
            addCriterion("family_illness >", value, "familyIllness");
            return (Criteria) this;
        }

        public Criteria andFamilyIllnessGreaterThanOrEqualTo(String value) {
            addCriterion("family_illness >=", value, "familyIllness");
            return (Criteria) this;
        }

        public Criteria andFamilyIllnessLessThan(String value) {
            addCriterion("family_illness <", value, "familyIllness");
            return (Criteria) this;
        }

        public Criteria andFamilyIllnessLessThanOrEqualTo(String value) {
            addCriterion("family_illness <=", value, "familyIllness");
            return (Criteria) this;
        }

        public Criteria andFamilyIllnessLike(String value) {
            addCriterion("family_illness like", value, "familyIllness");
            return (Criteria) this;
        }

        public Criteria andFamilyIllnessNotLike(String value) {
            addCriterion("family_illness not like", value, "familyIllness");
            return (Criteria) this;
        }

        public Criteria andFamilyIllnessIn(List<String> values) {
            addCriterion("family_illness in", values, "familyIllness");
            return (Criteria) this;
        }

        public Criteria andFamilyIllnessNotIn(List<String> values) {
            addCriterion("family_illness not in", values, "familyIllness");
            return (Criteria) this;
        }

        public Criteria andFamilyIllnessBetween(String value1, String value2) {
            addCriterion("family_illness between", value1, value2, "familyIllness");
            return (Criteria) this;
        }

        public Criteria andFamilyIllnessNotBetween(String value1, String value2) {
            addCriterion("family_illness not between", value1, value2, "familyIllness");
            return (Criteria) this;
        }

        public Criteria andAssistExamIsNull() {
            addCriterion("assist_exam is null");
            return (Criteria) this;
        }

        public Criteria andAssistExamIsNotNull() {
            addCriterion("assist_exam is not null");
            return (Criteria) this;
        }

        public Criteria andAssistExamEqualTo(String value) {
            addCriterion("assist_exam =", value, "assistExam");
            return (Criteria) this;
        }

        public Criteria andAssistExamNotEqualTo(String value) {
            addCriterion("assist_exam <>", value, "assistExam");
            return (Criteria) this;
        }

        public Criteria andAssistExamGreaterThan(String value) {
            addCriterion("assist_exam >", value, "assistExam");
            return (Criteria) this;
        }

        public Criteria andAssistExamGreaterThanOrEqualTo(String value) {
            addCriterion("assist_exam >=", value, "assistExam");
            return (Criteria) this;
        }

        public Criteria andAssistExamLessThan(String value) {
            addCriterion("assist_exam <", value, "assistExam");
            return (Criteria) this;
        }

        public Criteria andAssistExamLessThanOrEqualTo(String value) {
            addCriterion("assist_exam <=", value, "assistExam");
            return (Criteria) this;
        }

        public Criteria andAssistExamLike(String value) {
            addCriterion("assist_exam like", value, "assistExam");
            return (Criteria) this;
        }

        public Criteria andAssistExamNotLike(String value) {
            addCriterion("assist_exam not like", value, "assistExam");
            return (Criteria) this;
        }

        public Criteria andAssistExamIn(List<String> values) {
            addCriterion("assist_exam in", values, "assistExam");
            return (Criteria) this;
        }

        public Criteria andAssistExamNotIn(List<String> values) {
            addCriterion("assist_exam not in", values, "assistExam");
            return (Criteria) this;
        }

        public Criteria andAssistExamBetween(String value1, String value2) {
            addCriterion("assist_exam between", value1, value2, "assistExam");
            return (Criteria) this;
        }

        public Criteria andAssistExamNotBetween(String value1, String value2) {
            addCriterion("assist_exam not between", value1, value2, "assistExam");
            return (Criteria) this;
        }

        public Criteria andTreatSuggetionIsNull() {
            addCriterion("treat_suggetion is null");
            return (Criteria) this;
        }

        public Criteria andTreatSuggetionIsNotNull() {
            addCriterion("treat_suggetion is not null");
            return (Criteria) this;
        }

        public Criteria andTreatSuggetionEqualTo(String value) {
            addCriterion("treat_suggetion =", value, "treatSuggetion");
            return (Criteria) this;
        }

        public Criteria andTreatSuggetionNotEqualTo(String value) {
            addCriterion("treat_suggetion <>", value, "treatSuggetion");
            return (Criteria) this;
        }

        public Criteria andTreatSuggetionGreaterThan(String value) {
            addCriterion("treat_suggetion >", value, "treatSuggetion");
            return (Criteria) this;
        }

        public Criteria andTreatSuggetionGreaterThanOrEqualTo(String value) {
            addCriterion("treat_suggetion >=", value, "treatSuggetion");
            return (Criteria) this;
        }

        public Criteria andTreatSuggetionLessThan(String value) {
            addCriterion("treat_suggetion <", value, "treatSuggetion");
            return (Criteria) this;
        }

        public Criteria andTreatSuggetionLessThanOrEqualTo(String value) {
            addCriterion("treat_suggetion <=", value, "treatSuggetion");
            return (Criteria) this;
        }

        public Criteria andTreatSuggetionLike(String value) {
            addCriterion("treat_suggetion like", value, "treatSuggetion");
            return (Criteria) this;
        }

        public Criteria andTreatSuggetionNotLike(String value) {
            addCriterion("treat_suggetion not like", value, "treatSuggetion");
            return (Criteria) this;
        }

        public Criteria andTreatSuggetionIn(List<String> values) {
            addCriterion("treat_suggetion in", values, "treatSuggetion");
            return (Criteria) this;
        }

        public Criteria andTreatSuggetionNotIn(List<String> values) {
            addCriterion("treat_suggetion not in", values, "treatSuggetion");
            return (Criteria) this;
        }

        public Criteria andTreatSuggetionBetween(String value1, String value2) {
            addCriterion("treat_suggetion between", value1, value2, "treatSuggetion");
            return (Criteria) this;
        }

        public Criteria andTreatSuggetionNotBetween(String value1, String value2) {
            addCriterion("treat_suggetion not between", value1, value2, "treatSuggetion");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cs_outp_emr
     *
     * @mbggenerated do_not_delete_during_merge Mon Jul 11 17:57:07 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cs_outp_emr
     *
     * @mbggenerated Mon Jul 11 17:57:07 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}