package com.huatuo.clinics.cms.db.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class CsOutpOrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cs_outp_order
     *
     * @mbggenerated Wed Apr 13 15:32:39 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cs_outp_order
     *
     * @mbggenerated Wed Apr 13 15:32:39 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cs_outp_order
     *
     * @mbggenerated Wed Apr 13 15:32:39 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_outp_order
     *
     * @mbggenerated Wed Apr 13 15:32:39 CST 2016
     */
    public CsOutpOrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_outp_order
     *
     * @mbggenerated Wed Apr 13 15:32:39 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_outp_order
     *
     * @mbggenerated Wed Apr 13 15:32:39 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_outp_order
     *
     * @mbggenerated Wed Apr 13 15:32:39 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_outp_order
     *
     * @mbggenerated Wed Apr 13 15:32:39 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_outp_order
     *
     * @mbggenerated Wed Apr 13 15:32:39 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_outp_order
     *
     * @mbggenerated Wed Apr 13 15:32:39 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_outp_order
     *
     * @mbggenerated Wed Apr 13 15:32:39 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_outp_order
     *
     * @mbggenerated Wed Apr 13 15:32:39 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_outp_order
     *
     * @mbggenerated Wed Apr 13 15:32:39 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_outp_order
     *
     * @mbggenerated Wed Apr 13 15:32:39 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cs_outp_order
     *
     * @mbggenerated Wed Apr 13 15:32:39 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andOrdIdIsNull() {
            addCriterion("ord_id is null");
            return (Criteria) this;
        }

        public Criteria andOrdIdIsNotNull() {
            addCriterion("ord_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrdIdEqualTo(String value) {
            addCriterion("ord_id =", value, "ordId");
            return (Criteria) this;
        }

        public Criteria andOrdIdNotEqualTo(String value) {
            addCriterion("ord_id <>", value, "ordId");
            return (Criteria) this;
        }

        public Criteria andOrdIdGreaterThan(String value) {
            addCriterion("ord_id >", value, "ordId");
            return (Criteria) this;
        }

        public Criteria andOrdIdGreaterThanOrEqualTo(String value) {
            addCriterion("ord_id >=", value, "ordId");
            return (Criteria) this;
        }

        public Criteria andOrdIdLessThan(String value) {
            addCriterion("ord_id <", value, "ordId");
            return (Criteria) this;
        }

        public Criteria andOrdIdLessThanOrEqualTo(String value) {
            addCriterion("ord_id <=", value, "ordId");
            return (Criteria) this;
        }

        public Criteria andOrdIdLike(String value) {
            addCriterion("ord_id like", value, "ordId");
            return (Criteria) this;
        }

        public Criteria andOrdIdNotLike(String value) {
            addCriterion("ord_id not like", value, "ordId");
            return (Criteria) this;
        }

        public Criteria andOrdIdIn(List<String> values) {
            addCriterion("ord_id in", values, "ordId");
            return (Criteria) this;
        }

        public Criteria andOrdIdNotIn(List<String> values) {
            addCriterion("ord_id not in", values, "ordId");
            return (Criteria) this;
        }

        public Criteria andOrdIdBetween(String value1, String value2) {
            addCriterion("ord_id between", value1, value2, "ordId");
            return (Criteria) this;
        }

        public Criteria andOrdIdNotBetween(String value1, String value2) {
            addCriterion("ord_id not between", value1, value2, "ordId");
            return (Criteria) this;
        }

        public Criteria andVistiIdIsNull() {
            addCriterion("visti_id is null");
            return (Criteria) this;
        }

        public Criteria andVistiIdIsNotNull() {
            addCriterion("visti_id is not null");
            return (Criteria) this;
        }

        public Criteria andVistiIdEqualTo(String value) {
            addCriterion("visti_id =", value, "vistiId");
            return (Criteria) this;
        }

        public Criteria andVistiIdNotEqualTo(String value) {
            addCriterion("visti_id <>", value, "vistiId");
            return (Criteria) this;
        }

        public Criteria andVistiIdGreaterThan(String value) {
            addCriterion("visti_id >", value, "vistiId");
            return (Criteria) this;
        }

        public Criteria andVistiIdGreaterThanOrEqualTo(String value) {
            addCriterion("visti_id >=", value, "vistiId");
            return (Criteria) this;
        }

        public Criteria andVistiIdLessThan(String value) {
            addCriterion("visti_id <", value, "vistiId");
            return (Criteria) this;
        }

        public Criteria andVistiIdLessThanOrEqualTo(String value) {
            addCriterion("visti_id <=", value, "vistiId");
            return (Criteria) this;
        }

        public Criteria andVistiIdLike(String value) {
            addCriterion("visti_id like", value, "vistiId");
            return (Criteria) this;
        }

        public Criteria andVistiIdNotLike(String value) {
            addCriterion("visti_id not like", value, "vistiId");
            return (Criteria) this;
        }

        public Criteria andVistiIdIn(List<String> values) {
            addCriterion("visti_id in", values, "vistiId");
            return (Criteria) this;
        }

        public Criteria andVistiIdNotIn(List<String> values) {
            addCriterion("visti_id not in", values, "vistiId");
            return (Criteria) this;
        }

        public Criteria andVistiIdBetween(String value1, String value2) {
            addCriterion("visti_id between", value1, value2, "vistiId");
            return (Criteria) this;
        }

        public Criteria andVistiIdNotBetween(String value1, String value2) {
            addCriterion("visti_id not between", value1, value2, "vistiId");
            return (Criteria) this;
        }

        public Criteria andOrdNoIsNull() {
            addCriterion("ord_no is null");
            return (Criteria) this;
        }

        public Criteria andOrdNoIsNotNull() {
            addCriterion("ord_no is not null");
            return (Criteria) this;
        }

        public Criteria andOrdNoEqualTo(String value) {
            addCriterion("ord_no =", value, "ordNo");
            return (Criteria) this;
        }

        public Criteria andOrdNoNotEqualTo(String value) {
            addCriterion("ord_no <>", value, "ordNo");
            return (Criteria) this;
        }

        public Criteria andOrdNoGreaterThan(String value) {
            addCriterion("ord_no >", value, "ordNo");
            return (Criteria) this;
        }

        public Criteria andOrdNoGreaterThanOrEqualTo(String value) {
            addCriterion("ord_no >=", value, "ordNo");
            return (Criteria) this;
        }

        public Criteria andOrdNoLessThan(String value) {
            addCriterion("ord_no <", value, "ordNo");
            return (Criteria) this;
        }

        public Criteria andOrdNoLessThanOrEqualTo(String value) {
            addCriterion("ord_no <=", value, "ordNo");
            return (Criteria) this;
        }

        public Criteria andOrdNoLike(String value) {
            addCriterion("ord_no like", value, "ordNo");
            return (Criteria) this;
        }

        public Criteria andOrdNoNotLike(String value) {
            addCriterion("ord_no not like", value, "ordNo");
            return (Criteria) this;
        }

        public Criteria andOrdNoIn(List<String> values) {
            addCriterion("ord_no in", values, "ordNo");
            return (Criteria) this;
        }

        public Criteria andOrdNoNotIn(List<String> values) {
            addCriterion("ord_no not in", values, "ordNo");
            return (Criteria) this;
        }

        public Criteria andOrdNoBetween(String value1, String value2) {
            addCriterion("ord_no between", value1, value2, "ordNo");
            return (Criteria) this;
        }

        public Criteria andOrdNoNotBetween(String value1, String value2) {
            addCriterion("ord_no not between", value1, value2, "ordNo");
            return (Criteria) this;
        }

        public Criteria andOrgIdIsNull() {
            addCriterion("org_id is null");
            return (Criteria) this;
        }

        public Criteria andOrgIdIsNotNull() {
            addCriterion("org_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrgIdEqualTo(String value) {
            addCriterion("org_id =", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotEqualTo(String value) {
            addCriterion("org_id <>", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdGreaterThan(String value) {
            addCriterion("org_id >", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdGreaterThanOrEqualTo(String value) {
            addCriterion("org_id >=", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdLessThan(String value) {
            addCriterion("org_id <", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdLessThanOrEqualTo(String value) {
            addCriterion("org_id <=", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdLike(String value) {
            addCriterion("org_id like", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotLike(String value) {
            addCriterion("org_id not like", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdIn(List<String> values) {
            addCriterion("org_id in", values, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotIn(List<String> values) {
            addCriterion("org_id not in", values, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdBetween(String value1, String value2) {
            addCriterion("org_id between", value1, value2, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotBetween(String value1, String value2) {
            addCriterion("org_id not between", value1, value2, "orgId");
            return (Criteria) this;
        }

        public Criteria andVistiNoIsNull() {
            addCriterion("visti_no is null");
            return (Criteria) this;
        }

        public Criteria andVistiNoIsNotNull() {
            addCriterion("visti_no is not null");
            return (Criteria) this;
        }

        public Criteria andVistiNoEqualTo(Integer value) {
            addCriterion("visti_no =", value, "vistiNo");
            return (Criteria) this;
        }

        public Criteria andVistiNoNotEqualTo(Integer value) {
            addCriterion("visti_no <>", value, "vistiNo");
            return (Criteria) this;
        }

        public Criteria andVistiNoGreaterThan(Integer value) {
            addCriterion("visti_no >", value, "vistiNo");
            return (Criteria) this;
        }

        public Criteria andVistiNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("visti_no >=", value, "vistiNo");
            return (Criteria) this;
        }

        public Criteria andVistiNoLessThan(Integer value) {
            addCriterion("visti_no <", value, "vistiNo");
            return (Criteria) this;
        }

        public Criteria andVistiNoLessThanOrEqualTo(Integer value) {
            addCriterion("visti_no <=", value, "vistiNo");
            return (Criteria) this;
        }

        public Criteria andVistiNoIn(List<Integer> values) {
            addCriterion("visti_no in", values, "vistiNo");
            return (Criteria) this;
        }

        public Criteria andVistiNoNotIn(List<Integer> values) {
            addCriterion("visti_no not in", values, "vistiNo");
            return (Criteria) this;
        }

        public Criteria andVistiNoBetween(Integer value1, Integer value2) {
            addCriterion("visti_no between", value1, value2, "vistiNo");
            return (Criteria) this;
        }

        public Criteria andVistiNoNotBetween(Integer value1, Integer value2) {
            addCriterion("visti_no not between", value1, value2, "vistiNo");
            return (Criteria) this;
        }

        public Criteria andVisitDateIsNull() {
            addCriterion("visit_date is null");
            return (Criteria) this;
        }

        public Criteria andVisitDateIsNotNull() {
            addCriterion("visit_date is not null");
            return (Criteria) this;
        }

        public Criteria andVisitDateEqualTo(Date value) {
            addCriterionForJDBCDate("visit_date =", value, "visitDate");
            return (Criteria) this;
        }

        public Criteria andVisitDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("visit_date <>", value, "visitDate");
            return (Criteria) this;
        }

        public Criteria andVisitDateGreaterThan(Date value) {
            addCriterionForJDBCDate("visit_date >", value, "visitDate");
            return (Criteria) this;
        }

        public Criteria andVisitDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("visit_date >=", value, "visitDate");
            return (Criteria) this;
        }

        public Criteria andVisitDateLessThan(Date value) {
            addCriterionForJDBCDate("visit_date <", value, "visitDate");
            return (Criteria) this;
        }

        public Criteria andVisitDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("visit_date <=", value, "visitDate");
            return (Criteria) this;
        }

        public Criteria andVisitDateIn(List<Date> values) {
            addCriterionForJDBCDate("visit_date in", values, "visitDate");
            return (Criteria) this;
        }

        public Criteria andVisitDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("visit_date not in", values, "visitDate");
            return (Criteria) this;
        }

        public Criteria andVisitDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("visit_date between", value1, value2, "visitDate");
            return (Criteria) this;
        }

        public Criteria andVisitDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("visit_date not between", value1, value2, "visitDate");
            return (Criteria) this;
        }

        public Criteria andOrdDepIdIsNull() {
            addCriterion("ord_dep_id is null");
            return (Criteria) this;
        }

        public Criteria andOrdDepIdIsNotNull() {
            addCriterion("ord_dep_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrdDepIdEqualTo(String value) {
            addCriterion("ord_dep_id =", value, "ordDepId");
            return (Criteria) this;
        }

        public Criteria andOrdDepIdNotEqualTo(String value) {
            addCriterion("ord_dep_id <>", value, "ordDepId");
            return (Criteria) this;
        }

        public Criteria andOrdDepIdGreaterThan(String value) {
            addCriterion("ord_dep_id >", value, "ordDepId");
            return (Criteria) this;
        }

        public Criteria andOrdDepIdGreaterThanOrEqualTo(String value) {
            addCriterion("ord_dep_id >=", value, "ordDepId");
            return (Criteria) this;
        }

        public Criteria andOrdDepIdLessThan(String value) {
            addCriterion("ord_dep_id <", value, "ordDepId");
            return (Criteria) this;
        }

        public Criteria andOrdDepIdLessThanOrEqualTo(String value) {
            addCriterion("ord_dep_id <=", value, "ordDepId");
            return (Criteria) this;
        }

        public Criteria andOrdDepIdLike(String value) {
            addCriterion("ord_dep_id like", value, "ordDepId");
            return (Criteria) this;
        }

        public Criteria andOrdDepIdNotLike(String value) {
            addCriterion("ord_dep_id not like", value, "ordDepId");
            return (Criteria) this;
        }

        public Criteria andOrdDepIdIn(List<String> values) {
            addCriterion("ord_dep_id in", values, "ordDepId");
            return (Criteria) this;
        }

        public Criteria andOrdDepIdNotIn(List<String> values) {
            addCriterion("ord_dep_id not in", values, "ordDepId");
            return (Criteria) this;
        }

        public Criteria andOrdDepIdBetween(String value1, String value2) {
            addCriterion("ord_dep_id between", value1, value2, "ordDepId");
            return (Criteria) this;
        }

        public Criteria andOrdDepIdNotBetween(String value1, String value2) {
            addCriterion("ord_dep_id not between", value1, value2, "ordDepId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdIsNull() {
            addCriterion("doctor_id is null");
            return (Criteria) this;
        }

        public Criteria andDoctorIdIsNotNull() {
            addCriterion("doctor_id is not null");
            return (Criteria) this;
        }

        public Criteria andDoctorIdEqualTo(String value) {
            addCriterion("doctor_id =", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdNotEqualTo(String value) {
            addCriterion("doctor_id <>", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdGreaterThan(String value) {
            addCriterion("doctor_id >", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdGreaterThanOrEqualTo(String value) {
            addCriterion("doctor_id >=", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdLessThan(String value) {
            addCriterion("doctor_id <", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdLessThanOrEqualTo(String value) {
            addCriterion("doctor_id <=", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdLike(String value) {
            addCriterion("doctor_id like", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdNotLike(String value) {
            addCriterion("doctor_id not like", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdIn(List<String> values) {
            addCriterion("doctor_id in", values, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdNotIn(List<String> values) {
            addCriterion("doctor_id not in", values, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdBetween(String value1, String value2) {
            addCriterion("doctor_id between", value1, value2, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdNotBetween(String value1, String value2) {
            addCriterion("doctor_id not between", value1, value2, "doctorId");
            return (Criteria) this;
        }

        public Criteria andOrderTypeIsNull() {
            addCriterion("order_type is null");
            return (Criteria) this;
        }

        public Criteria andOrderTypeIsNotNull() {
            addCriterion("order_type is not null");
            return (Criteria) this;
        }

        public Criteria andOrderTypeEqualTo(String value) {
            addCriterion("order_type =", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeNotEqualTo(String value) {
            addCriterion("order_type <>", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeGreaterThan(String value) {
            addCriterion("order_type >", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeGreaterThanOrEqualTo(String value) {
            addCriterion("order_type >=", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeLessThan(String value) {
            addCriterion("order_type <", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeLessThanOrEqualTo(String value) {
            addCriterion("order_type <=", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeLike(String value) {
            addCriterion("order_type like", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeNotLike(String value) {
            addCriterion("order_type not like", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeIn(List<String> values) {
            addCriterion("order_type in", values, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeNotIn(List<String> values) {
            addCriterion("order_type not in", values, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeBetween(String value1, String value2) {
            addCriterion("order_type between", value1, value2, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeNotBetween(String value1, String value2) {
            addCriterion("order_type not between", value1, value2, "orderType");
            return (Criteria) this;
        }

        public Criteria andDrugTypeIsNull() {
            addCriterion("drug_type is null");
            return (Criteria) this;
        }

        public Criteria andDrugTypeIsNotNull() {
            addCriterion("drug_type is not null");
            return (Criteria) this;
        }

        public Criteria andDrugTypeEqualTo(String value) {
            addCriterion("drug_type =", value, "drugType");
            return (Criteria) this;
        }

        public Criteria andDrugTypeNotEqualTo(String value) {
            addCriterion("drug_type <>", value, "drugType");
            return (Criteria) this;
        }

        public Criteria andDrugTypeGreaterThan(String value) {
            addCriterion("drug_type >", value, "drugType");
            return (Criteria) this;
        }

        public Criteria andDrugTypeGreaterThanOrEqualTo(String value) {
            addCriterion("drug_type >=", value, "drugType");
            return (Criteria) this;
        }

        public Criteria andDrugTypeLessThan(String value) {
            addCriterion("drug_type <", value, "drugType");
            return (Criteria) this;
        }

        public Criteria andDrugTypeLessThanOrEqualTo(String value) {
            addCriterion("drug_type <=", value, "drugType");
            return (Criteria) this;
        }

        public Criteria andDrugTypeLike(String value) {
            addCriterion("drug_type like", value, "drugType");
            return (Criteria) this;
        }

        public Criteria andDrugTypeNotLike(String value) {
            addCriterion("drug_type not like", value, "drugType");
            return (Criteria) this;
        }

        public Criteria andDrugTypeIn(List<String> values) {
            addCriterion("drug_type in", values, "drugType");
            return (Criteria) this;
        }

        public Criteria andDrugTypeNotIn(List<String> values) {
            addCriterion("drug_type not in", values, "drugType");
            return (Criteria) this;
        }

        public Criteria andDrugTypeBetween(String value1, String value2) {
            addCriterion("drug_type between", value1, value2, "drugType");
            return (Criteria) this;
        }

        public Criteria andDrugTypeNotBetween(String value1, String value2) {
            addCriterion("drug_type not between", value1, value2, "drugType");
            return (Criteria) this;
        }

        public Criteria andOrderMemoIsNull() {
            addCriterion("order_memo is null");
            return (Criteria) this;
        }

        public Criteria andOrderMemoIsNotNull() {
            addCriterion("order_memo is not null");
            return (Criteria) this;
        }

        public Criteria andOrderMemoEqualTo(String value) {
            addCriterion("order_memo =", value, "orderMemo");
            return (Criteria) this;
        }

        public Criteria andOrderMemoNotEqualTo(String value) {
            addCriterion("order_memo <>", value, "orderMemo");
            return (Criteria) this;
        }

        public Criteria andOrderMemoGreaterThan(String value) {
            addCriterion("order_memo >", value, "orderMemo");
            return (Criteria) this;
        }

        public Criteria andOrderMemoGreaterThanOrEqualTo(String value) {
            addCriterion("order_memo >=", value, "orderMemo");
            return (Criteria) this;
        }

        public Criteria andOrderMemoLessThan(String value) {
            addCriterion("order_memo <", value, "orderMemo");
            return (Criteria) this;
        }

        public Criteria andOrderMemoLessThanOrEqualTo(String value) {
            addCriterion("order_memo <=", value, "orderMemo");
            return (Criteria) this;
        }

        public Criteria andOrderMemoLike(String value) {
            addCriterion("order_memo like", value, "orderMemo");
            return (Criteria) this;
        }

        public Criteria andOrderMemoNotLike(String value) {
            addCriterion("order_memo not like", value, "orderMemo");
            return (Criteria) this;
        }

        public Criteria andOrderMemoIn(List<String> values) {
            addCriterion("order_memo in", values, "orderMemo");
            return (Criteria) this;
        }

        public Criteria andOrderMemoNotIn(List<String> values) {
            addCriterion("order_memo not in", values, "orderMemo");
            return (Criteria) this;
        }

        public Criteria andOrderMemoBetween(String value1, String value2) {
            addCriterion("order_memo between", value1, value2, "orderMemo");
            return (Criteria) this;
        }

        public Criteria andOrderMemoNotBetween(String value1, String value2) {
            addCriterion("order_memo not between", value1, value2, "orderMemo");
            return (Criteria) this;
        }

        public Criteria andAmoutIsNull() {
            addCriterion("amout is null");
            return (Criteria) this;
        }

        public Criteria andAmoutIsNotNull() {
            addCriterion("amout is not null");
            return (Criteria) this;
        }

        public Criteria andAmoutEqualTo(Float value) {
            addCriterion("amout =", value, "amout");
            return (Criteria) this;
        }

        public Criteria andAmoutNotEqualTo(Float value) {
            addCriterion("amout <>", value, "amout");
            return (Criteria) this;
        }

        public Criteria andAmoutGreaterThan(Float value) {
            addCriterion("amout >", value, "amout");
            return (Criteria) this;
        }

        public Criteria andAmoutGreaterThanOrEqualTo(Float value) {
            addCriterion("amout >=", value, "amout");
            return (Criteria) this;
        }

        public Criteria andAmoutLessThan(Float value) {
            addCriterion("amout <", value, "amout");
            return (Criteria) this;
        }

        public Criteria andAmoutLessThanOrEqualTo(Float value) {
            addCriterion("amout <=", value, "amout");
            return (Criteria) this;
        }

        public Criteria andAmoutIn(List<Float> values) {
            addCriterion("amout in", values, "amout");
            return (Criteria) this;
        }

        public Criteria andAmoutNotIn(List<Float> values) {
            addCriterion("amout not in", values, "amout");
            return (Criteria) this;
        }

        public Criteria andAmoutBetween(Float value1, Float value2) {
            addCriterion("amout between", value1, value2, "amout");
            return (Criteria) this;
        }

        public Criteria andAmoutNotBetween(Float value1, Float value2) {
            addCriterion("amout not between", value1, value2, "amout");
            return (Criteria) this;
        }

        public Criteria andValidFlgIsNull() {
            addCriterion("valid_flg is null");
            return (Criteria) this;
        }

        public Criteria andValidFlgIsNotNull() {
            addCriterion("valid_flg is not null");
            return (Criteria) this;
        }

        public Criteria andValidFlgEqualTo(String value) {
            addCriterion("valid_flg =", value, "validFlg");
            return (Criteria) this;
        }

        public Criteria andValidFlgNotEqualTo(String value) {
            addCriterion("valid_flg <>", value, "validFlg");
            return (Criteria) this;
        }

        public Criteria andValidFlgGreaterThan(String value) {
            addCriterion("valid_flg >", value, "validFlg");
            return (Criteria) this;
        }

        public Criteria andValidFlgGreaterThanOrEqualTo(String value) {
            addCriterion("valid_flg >=", value, "validFlg");
            return (Criteria) this;
        }

        public Criteria andValidFlgLessThan(String value) {
            addCriterion("valid_flg <", value, "validFlg");
            return (Criteria) this;
        }

        public Criteria andValidFlgLessThanOrEqualTo(String value) {
            addCriterion("valid_flg <=", value, "validFlg");
            return (Criteria) this;
        }

        public Criteria andValidFlgLike(String value) {
            addCriterion("valid_flg like", value, "validFlg");
            return (Criteria) this;
        }

        public Criteria andValidFlgNotLike(String value) {
            addCriterion("valid_flg not like", value, "validFlg");
            return (Criteria) this;
        }

        public Criteria andValidFlgIn(List<String> values) {
            addCriterion("valid_flg in", values, "validFlg");
            return (Criteria) this;
        }

        public Criteria andValidFlgNotIn(List<String> values) {
            addCriterion("valid_flg not in", values, "validFlg");
            return (Criteria) this;
        }

        public Criteria andValidFlgBetween(String value1, String value2) {
            addCriterion("valid_flg between", value1, value2, "validFlg");
            return (Criteria) this;
        }

        public Criteria andValidFlgNotBetween(String value1, String value2) {
            addCriterion("valid_flg not between", value1, value2, "validFlg");
            return (Criteria) this;
        }

        public Criteria andIsChargeIsNull() {
            addCriterion("is_charge is null");
            return (Criteria) this;
        }

        public Criteria andIsChargeIsNotNull() {
            addCriterion("is_charge is not null");
            return (Criteria) this;
        }

        public Criteria andIsChargeEqualTo(String value) {
            addCriterion("is_charge =", value, "isCharge");
            return (Criteria) this;
        }

        public Criteria andIsChargeNotEqualTo(String value) {
            addCriterion("is_charge <>", value, "isCharge");
            return (Criteria) this;
        }

        public Criteria andIsChargeGreaterThan(String value) {
            addCriterion("is_charge >", value, "isCharge");
            return (Criteria) this;
        }

        public Criteria andIsChargeGreaterThanOrEqualTo(String value) {
            addCriterion("is_charge >=", value, "isCharge");
            return (Criteria) this;
        }

        public Criteria andIsChargeLessThan(String value) {
            addCriterion("is_charge <", value, "isCharge");
            return (Criteria) this;
        }

        public Criteria andIsChargeLessThanOrEqualTo(String value) {
            addCriterion("is_charge <=", value, "isCharge");
            return (Criteria) this;
        }

        public Criteria andIsChargeLike(String value) {
            addCriterion("is_charge like", value, "isCharge");
            return (Criteria) this;
        }

        public Criteria andIsChargeNotLike(String value) {
            addCriterion("is_charge not like", value, "isCharge");
            return (Criteria) this;
        }

        public Criteria andIsChargeIn(List<String> values) {
            addCriterion("is_charge in", values, "isCharge");
            return (Criteria) this;
        }

        public Criteria andIsChargeNotIn(List<String> values) {
            addCriterion("is_charge not in", values, "isCharge");
            return (Criteria) this;
        }

        public Criteria andIsChargeBetween(String value1, String value2) {
            addCriterion("is_charge between", value1, value2, "isCharge");
            return (Criteria) this;
        }

        public Criteria andIsChargeNotBetween(String value1, String value2) {
            addCriterion("is_charge not between", value1, value2, "isCharge");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cs_outp_order
     *
     * @mbggenerated do_not_delete_during_merge Wed Apr 13 15:32:39 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cs_outp_order
     *
     * @mbggenerated Wed Apr 13 15:32:39 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}