package com.huatuo.clinics.cms.db.bean;

import java.util.ArrayList;
import java.util.List;

public class SmCliAreaSicknessInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sm_cli_area_sickness_info
     *
     * @mbggenerated Thu Aug 18 10:00:53 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sm_cli_area_sickness_info
     *
     * @mbggenerated Thu Aug 18 10:00:53 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sm_cli_area_sickness_info
     *
     * @mbggenerated Thu Aug 18 10:00:53 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_sickness_info
     *
     * @mbggenerated Thu Aug 18 10:00:53 CST 2016
     */
    public SmCliAreaSicknessInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_sickness_info
     *
     * @mbggenerated Thu Aug 18 10:00:53 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_sickness_info
     *
     * @mbggenerated Thu Aug 18 10:00:53 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_sickness_info
     *
     * @mbggenerated Thu Aug 18 10:00:53 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_sickness_info
     *
     * @mbggenerated Thu Aug 18 10:00:53 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_sickness_info
     *
     * @mbggenerated Thu Aug 18 10:00:53 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_sickness_info
     *
     * @mbggenerated Thu Aug 18 10:00:53 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_sickness_info
     *
     * @mbggenerated Thu Aug 18 10:00:53 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_sickness_info
     *
     * @mbggenerated Thu Aug 18 10:00:53 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_sickness_info
     *
     * @mbggenerated Thu Aug 18 10:00:53 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_sickness_info
     *
     * @mbggenerated Thu Aug 18 10:00:53 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sm_cli_area_sickness_info
     *
     * @mbggenerated Thu Aug 18 10:00:53 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAreaSicknessIdIsNull() {
            addCriterion("area_sickness_id is null");
            return (Criteria) this;
        }

        public Criteria andAreaSicknessIdIsNotNull() {
            addCriterion("area_sickness_id is not null");
            return (Criteria) this;
        }

        public Criteria andAreaSicknessIdEqualTo(String value) {
            addCriterion("area_sickness_id =", value, "areaSicknessId");
            return (Criteria) this;
        }

        public Criteria andAreaSicknessIdNotEqualTo(String value) {
            addCriterion("area_sickness_id <>", value, "areaSicknessId");
            return (Criteria) this;
        }

        public Criteria andAreaSicknessIdGreaterThan(String value) {
            addCriterion("area_sickness_id >", value, "areaSicknessId");
            return (Criteria) this;
        }

        public Criteria andAreaSicknessIdGreaterThanOrEqualTo(String value) {
            addCriterion("area_sickness_id >=", value, "areaSicknessId");
            return (Criteria) this;
        }

        public Criteria andAreaSicknessIdLessThan(String value) {
            addCriterion("area_sickness_id <", value, "areaSicknessId");
            return (Criteria) this;
        }

        public Criteria andAreaSicknessIdLessThanOrEqualTo(String value) {
            addCriterion("area_sickness_id <=", value, "areaSicknessId");
            return (Criteria) this;
        }

        public Criteria andAreaSicknessIdLike(String value) {
            addCriterion("area_sickness_id like", value, "areaSicknessId");
            return (Criteria) this;
        }

        public Criteria andAreaSicknessIdNotLike(String value) {
            addCriterion("area_sickness_id not like", value, "areaSicknessId");
            return (Criteria) this;
        }

        public Criteria andAreaSicknessIdIn(List<String> values) {
            addCriterion("area_sickness_id in", values, "areaSicknessId");
            return (Criteria) this;
        }

        public Criteria andAreaSicknessIdNotIn(List<String> values) {
            addCriterion("area_sickness_id not in", values, "areaSicknessId");
            return (Criteria) this;
        }

        public Criteria andAreaSicknessIdBetween(String value1, String value2) {
            addCriterion("area_sickness_id between", value1, value2, "areaSicknessId");
            return (Criteria) this;
        }

        public Criteria andAreaSicknessIdNotBetween(String value1, String value2) {
            addCriterion("area_sickness_id not between", value1, value2, "areaSicknessId");
            return (Criteria) this;
        }

        public Criteria andAreaCoverIdIsNull() {
            addCriterion("area_cover_id is null");
            return (Criteria) this;
        }

        public Criteria andAreaCoverIdIsNotNull() {
            addCriterion("area_cover_id is not null");
            return (Criteria) this;
        }

        public Criteria andAreaCoverIdEqualTo(String value) {
            addCriterion("area_cover_id =", value, "areaCoverId");
            return (Criteria) this;
        }

        public Criteria andAreaCoverIdNotEqualTo(String value) {
            addCriterion("area_cover_id <>", value, "areaCoverId");
            return (Criteria) this;
        }

        public Criteria andAreaCoverIdGreaterThan(String value) {
            addCriterion("area_cover_id >", value, "areaCoverId");
            return (Criteria) this;
        }

        public Criteria andAreaCoverIdGreaterThanOrEqualTo(String value) {
            addCriterion("area_cover_id >=", value, "areaCoverId");
            return (Criteria) this;
        }

        public Criteria andAreaCoverIdLessThan(String value) {
            addCriterion("area_cover_id <", value, "areaCoverId");
            return (Criteria) this;
        }

        public Criteria andAreaCoverIdLessThanOrEqualTo(String value) {
            addCriterion("area_cover_id <=", value, "areaCoverId");
            return (Criteria) this;
        }

        public Criteria andAreaCoverIdLike(String value) {
            addCriterion("area_cover_id like", value, "areaCoverId");
            return (Criteria) this;
        }

        public Criteria andAreaCoverIdNotLike(String value) {
            addCriterion("area_cover_id not like", value, "areaCoverId");
            return (Criteria) this;
        }

        public Criteria andAreaCoverIdIn(List<String> values) {
            addCriterion("area_cover_id in", values, "areaCoverId");
            return (Criteria) this;
        }

        public Criteria andAreaCoverIdNotIn(List<String> values) {
            addCriterion("area_cover_id not in", values, "areaCoverId");
            return (Criteria) this;
        }

        public Criteria andAreaCoverIdBetween(String value1, String value2) {
            addCriterion("area_cover_id between", value1, value2, "areaCoverId");
            return (Criteria) this;
        }

        public Criteria andAreaCoverIdNotBetween(String value1, String value2) {
            addCriterion("area_cover_id not between", value1, value2, "areaCoverId");
            return (Criteria) this;
        }

        public Criteria andSicknessCodeIsNull() {
            addCriterion("sickness_code is null");
            return (Criteria) this;
        }

        public Criteria andSicknessCodeIsNotNull() {
            addCriterion("sickness_code is not null");
            return (Criteria) this;
        }

        public Criteria andSicknessCodeEqualTo(String value) {
            addCriterion("sickness_code =", value, "sicknessCode");
            return (Criteria) this;
        }

        public Criteria andSicknessCodeNotEqualTo(String value) {
            addCriterion("sickness_code <>", value, "sicknessCode");
            return (Criteria) this;
        }

        public Criteria andSicknessCodeGreaterThan(String value) {
            addCriterion("sickness_code >", value, "sicknessCode");
            return (Criteria) this;
        }

        public Criteria andSicknessCodeGreaterThanOrEqualTo(String value) {
            addCriterion("sickness_code >=", value, "sicknessCode");
            return (Criteria) this;
        }

        public Criteria andSicknessCodeLessThan(String value) {
            addCriterion("sickness_code <", value, "sicknessCode");
            return (Criteria) this;
        }

        public Criteria andSicknessCodeLessThanOrEqualTo(String value) {
            addCriterion("sickness_code <=", value, "sicknessCode");
            return (Criteria) this;
        }

        public Criteria andSicknessCodeLike(String value) {
            addCriterion("sickness_code like", value, "sicknessCode");
            return (Criteria) this;
        }

        public Criteria andSicknessCodeNotLike(String value) {
            addCriterion("sickness_code not like", value, "sicknessCode");
            return (Criteria) this;
        }

        public Criteria andSicknessCodeIn(List<String> values) {
            addCriterion("sickness_code in", values, "sicknessCode");
            return (Criteria) this;
        }

        public Criteria andSicknessCodeNotIn(List<String> values) {
            addCriterion("sickness_code not in", values, "sicknessCode");
            return (Criteria) this;
        }

        public Criteria andSicknessCodeBetween(String value1, String value2) {
            addCriterion("sickness_code between", value1, value2, "sicknessCode");
            return (Criteria) this;
        }

        public Criteria andSicknessCodeNotBetween(String value1, String value2) {
            addCriterion("sickness_code not between", value1, value2, "sicknessCode");
            return (Criteria) this;
        }

        public Criteria andSicknessNameIsNull() {
            addCriterion("sickness_name is null");
            return (Criteria) this;
        }

        public Criteria andSicknessNameIsNotNull() {
            addCriterion("sickness_name is not null");
            return (Criteria) this;
        }

        public Criteria andSicknessNameEqualTo(String value) {
            addCriterion("sickness_name =", value, "sicknessName");
            return (Criteria) this;
        }

        public Criteria andSicknessNameNotEqualTo(String value) {
            addCriterion("sickness_name <>", value, "sicknessName");
            return (Criteria) this;
        }

        public Criteria andSicknessNameGreaterThan(String value) {
            addCriterion("sickness_name >", value, "sicknessName");
            return (Criteria) this;
        }

        public Criteria andSicknessNameGreaterThanOrEqualTo(String value) {
            addCriterion("sickness_name >=", value, "sicknessName");
            return (Criteria) this;
        }

        public Criteria andSicknessNameLessThan(String value) {
            addCriterion("sickness_name <", value, "sicknessName");
            return (Criteria) this;
        }

        public Criteria andSicknessNameLessThanOrEqualTo(String value) {
            addCriterion("sickness_name <=", value, "sicknessName");
            return (Criteria) this;
        }

        public Criteria andSicknessNameLike(String value) {
            addCriterion("sickness_name like", value, "sicknessName");
            return (Criteria) this;
        }

        public Criteria andSicknessNameNotLike(String value) {
            addCriterion("sickness_name not like", value, "sicknessName");
            return (Criteria) this;
        }

        public Criteria andSicknessNameIn(List<String> values) {
            addCriterion("sickness_name in", values, "sicknessName");
            return (Criteria) this;
        }

        public Criteria andSicknessNameNotIn(List<String> values) {
            addCriterion("sickness_name not in", values, "sicknessName");
            return (Criteria) this;
        }

        public Criteria andSicknessNameBetween(String value1, String value2) {
            addCriterion("sickness_name between", value1, value2, "sicknessName");
            return (Criteria) this;
        }

        public Criteria andSicknessNameNotBetween(String value1, String value2) {
            addCriterion("sickness_name not between", value1, value2, "sicknessName");
            return (Criteria) this;
        }

        public Criteria andSicknessQtyIsNull() {
            addCriterion("sickness_qty is null");
            return (Criteria) this;
        }

        public Criteria andSicknessQtyIsNotNull() {
            addCriterion("sickness_qty is not null");
            return (Criteria) this;
        }

        public Criteria andSicknessQtyEqualTo(Integer value) {
            addCriterion("sickness_qty =", value, "sicknessQty");
            return (Criteria) this;
        }

        public Criteria andSicknessQtyNotEqualTo(Integer value) {
            addCriterion("sickness_qty <>", value, "sicknessQty");
            return (Criteria) this;
        }

        public Criteria andSicknessQtyGreaterThan(Integer value) {
            addCriterion("sickness_qty >", value, "sicknessQty");
            return (Criteria) this;
        }

        public Criteria andSicknessQtyGreaterThanOrEqualTo(Integer value) {
            addCriterion("sickness_qty >=", value, "sicknessQty");
            return (Criteria) this;
        }

        public Criteria andSicknessQtyLessThan(Integer value) {
            addCriterion("sickness_qty <", value, "sicknessQty");
            return (Criteria) this;
        }

        public Criteria andSicknessQtyLessThanOrEqualTo(Integer value) {
            addCriterion("sickness_qty <=", value, "sicknessQty");
            return (Criteria) this;
        }

        public Criteria andSicknessQtyIn(List<Integer> values) {
            addCriterion("sickness_qty in", values, "sicknessQty");
            return (Criteria) this;
        }

        public Criteria andSicknessQtyNotIn(List<Integer> values) {
            addCriterion("sickness_qty not in", values, "sicknessQty");
            return (Criteria) this;
        }

        public Criteria andSicknessQtyBetween(Integer value1, Integer value2) {
            addCriterion("sickness_qty between", value1, value2, "sicknessQty");
            return (Criteria) this;
        }

        public Criteria andSicknessQtyNotBetween(Integer value1, Integer value2) {
            addCriterion("sickness_qty not between", value1, value2, "sicknessQty");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sm_cli_area_sickness_info
     *
     * @mbggenerated do_not_delete_during_merge Thu Aug 18 10:00:53 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sm_cli_area_sickness_info
     *
     * @mbggenerated Thu Aug 18 10:00:53 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}