package com.huatuo.clinics.cms.db.bean;

import java.util.Date;

public class SmCliAreaCover {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_cli_area_cover.area_cover_id
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    private String areaCoverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_cli_area_cover.area_code
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    private String areaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_cli_area_cover.area_name
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    private String areaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_cli_area_cover.parent_area_name
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    private String parentAreaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_cli_area_cover.parent_area_code
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    private String parentAreaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_cli_area_cover.year
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    private Integer year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_cli_area_cover.month
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    private Integer month;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_cli_area_cover.day
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    private Integer day;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_cli_area_cover.clinic_qty
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    private Integer clinicQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_cli_area_cover.doctor_qty
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    private Integer doctorQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_cli_area_cover.nurse_qty
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    private Integer nurseQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_cli_area_cover.other_qty
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    private Integer otherQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_cli_area_cover.record_date
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    private Date recordDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_cli_area_cover.update_date
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_cli_area_cover.area_cover_id
     *
     * @return the value of sm_cli_area_cover.area_cover_id
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    public String getAreaCoverId() {
        return areaCoverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_cli_area_cover.area_cover_id
     *
     * @param areaCoverId the value for sm_cli_area_cover.area_cover_id
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    public void setAreaCoverId(String areaCoverId) {
        this.areaCoverId = areaCoverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_cli_area_cover.area_code
     *
     * @return the value of sm_cli_area_cover.area_code
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_cli_area_cover.area_code
     *
     * @param areaCode the value for sm_cli_area_cover.area_code
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_cli_area_cover.area_name
     *
     * @return the value of sm_cli_area_cover.area_name
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_cli_area_cover.area_name
     *
     * @param areaName the value for sm_cli_area_cover.area_name
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_cli_area_cover.parent_area_name
     *
     * @return the value of sm_cli_area_cover.parent_area_name
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    public String getParentAreaName() {
        return parentAreaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_cli_area_cover.parent_area_name
     *
     * @param parentAreaName the value for sm_cli_area_cover.parent_area_name
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    public void setParentAreaName(String parentAreaName) {
        this.parentAreaName = parentAreaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_cli_area_cover.parent_area_code
     *
     * @return the value of sm_cli_area_cover.parent_area_code
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    public String getParentAreaCode() {
        return parentAreaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_cli_area_cover.parent_area_code
     *
     * @param parentAreaCode the value for sm_cli_area_cover.parent_area_code
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    public void setParentAreaCode(String parentAreaCode) {
        this.parentAreaCode = parentAreaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_cli_area_cover.year
     *
     * @return the value of sm_cli_area_cover.year
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_cli_area_cover.year
     *
     * @param year the value for sm_cli_area_cover.year
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_cli_area_cover.month
     *
     * @return the value of sm_cli_area_cover.month
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    public Integer getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_cli_area_cover.month
     *
     * @param month the value for sm_cli_area_cover.month
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    public void setMonth(Integer month) {
        this.month = month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_cli_area_cover.day
     *
     * @return the value of sm_cli_area_cover.day
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    public Integer getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_cli_area_cover.day
     *
     * @param day the value for sm_cli_area_cover.day
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    public void setDay(Integer day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_cli_area_cover.clinic_qty
     *
     * @return the value of sm_cli_area_cover.clinic_qty
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    public Integer getClinicQty() {
        return clinicQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_cli_area_cover.clinic_qty
     *
     * @param clinicQty the value for sm_cli_area_cover.clinic_qty
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    public void setClinicQty(Integer clinicQty) {
        this.clinicQty = clinicQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_cli_area_cover.doctor_qty
     *
     * @return the value of sm_cli_area_cover.doctor_qty
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    public Integer getDoctorQty() {
        return doctorQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_cli_area_cover.doctor_qty
     *
     * @param doctorQty the value for sm_cli_area_cover.doctor_qty
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    public void setDoctorQty(Integer doctorQty) {
        this.doctorQty = doctorQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_cli_area_cover.nurse_qty
     *
     * @return the value of sm_cli_area_cover.nurse_qty
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    public Integer getNurseQty() {
        return nurseQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_cli_area_cover.nurse_qty
     *
     * @param nurseQty the value for sm_cli_area_cover.nurse_qty
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    public void setNurseQty(Integer nurseQty) {
        this.nurseQty = nurseQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_cli_area_cover.other_qty
     *
     * @return the value of sm_cli_area_cover.other_qty
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    public Integer getOtherQty() {
        return otherQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_cli_area_cover.other_qty
     *
     * @param otherQty the value for sm_cli_area_cover.other_qty
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    public void setOtherQty(Integer otherQty) {
        this.otherQty = otherQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_cli_area_cover.record_date
     *
     * @return the value of sm_cli_area_cover.record_date
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    public Date getRecordDate() {
        return recordDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_cli_area_cover.record_date
     *
     * @param recordDate the value for sm_cli_area_cover.record_date
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    public void setRecordDate(Date recordDate) {
        this.recordDate = recordDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_cli_area_cover.update_date
     *
     * @return the value of sm_cli_area_cover.update_date
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_cli_area_cover.update_date
     *
     * @param updateDate the value for sm_cli_area_cover.update_date
     *
     * @mbggenerated Thu Aug 11 17:33:42 CST 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}