package com.huatuo.clinics.cms.db.bean;

import java.util.ArrayList;
import java.util.List;

public class SmCliAreaCoverDtlExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sm_cli_area_cover_dtl
     *
     * @mbggenerated Thu Aug 11 17:36:41 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sm_cli_area_cover_dtl
     *
     * @mbggenerated Thu Aug 11 17:36:41 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sm_cli_area_cover_dtl
     *
     * @mbggenerated Thu Aug 11 17:36:41 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_cover_dtl
     *
     * @mbggenerated Thu Aug 11 17:36:41 CST 2016
     */
    public SmCliAreaCoverDtlExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_cover_dtl
     *
     * @mbggenerated Thu Aug 11 17:36:41 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_cover_dtl
     *
     * @mbggenerated Thu Aug 11 17:36:41 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_cover_dtl
     *
     * @mbggenerated Thu Aug 11 17:36:41 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_cover_dtl
     *
     * @mbggenerated Thu Aug 11 17:36:41 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_cover_dtl
     *
     * @mbggenerated Thu Aug 11 17:36:41 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_cover_dtl
     *
     * @mbggenerated Thu Aug 11 17:36:41 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_cover_dtl
     *
     * @mbggenerated Thu Aug 11 17:36:41 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_cover_dtl
     *
     * @mbggenerated Thu Aug 11 17:36:41 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_cover_dtl
     *
     * @mbggenerated Thu Aug 11 17:36:41 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_cli_area_cover_dtl
     *
     * @mbggenerated Thu Aug 11 17:36:41 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sm_cli_area_cover_dtl
     *
     * @mbggenerated Thu Aug 11 17:36:41 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAreaCoverDtlIdIsNull() {
            addCriterion("area_cover_dtl_id is null");
            return (Criteria) this;
        }

        public Criteria andAreaCoverDtlIdIsNotNull() {
            addCriterion("area_cover_dtl_id is not null");
            return (Criteria) this;
        }

        public Criteria andAreaCoverDtlIdEqualTo(String value) {
            addCriterion("area_cover_dtl_id =", value, "areaCoverDtlId");
            return (Criteria) this;
        }

        public Criteria andAreaCoverDtlIdNotEqualTo(String value) {
            addCriterion("area_cover_dtl_id <>", value, "areaCoverDtlId");
            return (Criteria) this;
        }

        public Criteria andAreaCoverDtlIdGreaterThan(String value) {
            addCriterion("area_cover_dtl_id >", value, "areaCoverDtlId");
            return (Criteria) this;
        }

        public Criteria andAreaCoverDtlIdGreaterThanOrEqualTo(String value) {
            addCriterion("area_cover_dtl_id >=", value, "areaCoverDtlId");
            return (Criteria) this;
        }

        public Criteria andAreaCoverDtlIdLessThan(String value) {
            addCriterion("area_cover_dtl_id <", value, "areaCoverDtlId");
            return (Criteria) this;
        }

        public Criteria andAreaCoverDtlIdLessThanOrEqualTo(String value) {
            addCriterion("area_cover_dtl_id <=", value, "areaCoverDtlId");
            return (Criteria) this;
        }

        public Criteria andAreaCoverDtlIdLike(String value) {
            addCriterion("area_cover_dtl_id like", value, "areaCoverDtlId");
            return (Criteria) this;
        }

        public Criteria andAreaCoverDtlIdNotLike(String value) {
            addCriterion("area_cover_dtl_id not like", value, "areaCoverDtlId");
            return (Criteria) this;
        }

        public Criteria andAreaCoverDtlIdIn(List<String> values) {
            addCriterion("area_cover_dtl_id in", values, "areaCoverDtlId");
            return (Criteria) this;
        }

        public Criteria andAreaCoverDtlIdNotIn(List<String> values) {
            addCriterion("area_cover_dtl_id not in", values, "areaCoverDtlId");
            return (Criteria) this;
        }

        public Criteria andAreaCoverDtlIdBetween(String value1, String value2) {
            addCriterion("area_cover_dtl_id between", value1, value2, "areaCoverDtlId");
            return (Criteria) this;
        }

        public Criteria andAreaCoverDtlIdNotBetween(String value1, String value2) {
            addCriterion("area_cover_dtl_id not between", value1, value2, "areaCoverDtlId");
            return (Criteria) this;
        }

        public Criteria andAreaCoverIdIsNull() {
            addCriterion("area_cover_id is null");
            return (Criteria) this;
        }

        public Criteria andAreaCoverIdIsNotNull() {
            addCriterion("area_cover_id is not null");
            return (Criteria) this;
        }

        public Criteria andAreaCoverIdEqualTo(String value) {
            addCriterion("area_cover_id =", value, "areaCoverId");
            return (Criteria) this;
        }

        public Criteria andAreaCoverIdNotEqualTo(String value) {
            addCriterion("area_cover_id <>", value, "areaCoverId");
            return (Criteria) this;
        }

        public Criteria andAreaCoverIdGreaterThan(String value) {
            addCriterion("area_cover_id >", value, "areaCoverId");
            return (Criteria) this;
        }

        public Criteria andAreaCoverIdGreaterThanOrEqualTo(String value) {
            addCriterion("area_cover_id >=", value, "areaCoverId");
            return (Criteria) this;
        }

        public Criteria andAreaCoverIdLessThan(String value) {
            addCriterion("area_cover_id <", value, "areaCoverId");
            return (Criteria) this;
        }

        public Criteria andAreaCoverIdLessThanOrEqualTo(String value) {
            addCriterion("area_cover_id <=", value, "areaCoverId");
            return (Criteria) this;
        }

        public Criteria andAreaCoverIdLike(String value) {
            addCriterion("area_cover_id like", value, "areaCoverId");
            return (Criteria) this;
        }

        public Criteria andAreaCoverIdNotLike(String value) {
            addCriterion("area_cover_id not like", value, "areaCoverId");
            return (Criteria) this;
        }

        public Criteria andAreaCoverIdIn(List<String> values) {
            addCriterion("area_cover_id in", values, "areaCoverId");
            return (Criteria) this;
        }

        public Criteria andAreaCoverIdNotIn(List<String> values) {
            addCriterion("area_cover_id not in", values, "areaCoverId");
            return (Criteria) this;
        }

        public Criteria andAreaCoverIdBetween(String value1, String value2) {
            addCriterion("area_cover_id between", value1, value2, "areaCoverId");
            return (Criteria) this;
        }

        public Criteria andAreaCoverIdNotBetween(String value1, String value2) {
            addCriterion("area_cover_id not between", value1, value2, "areaCoverId");
            return (Criteria) this;
        }

        public Criteria andSourceIsNull() {
            addCriterion("source is null");
            return (Criteria) this;
        }

        public Criteria andSourceIsNotNull() {
            addCriterion("source is not null");
            return (Criteria) this;
        }

        public Criteria andSourceEqualTo(String value) {
            addCriterion("source =", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotEqualTo(String value) {
            addCriterion("source <>", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThan(String value) {
            addCriterion("source >", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThanOrEqualTo(String value) {
            addCriterion("source >=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThan(String value) {
            addCriterion("source <", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThanOrEqualTo(String value) {
            addCriterion("source <=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLike(String value) {
            addCriterion("source like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotLike(String value) {
            addCriterion("source not like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceIn(List<String> values) {
            addCriterion("source in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotIn(List<String> values) {
            addCriterion("source not in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceBetween(String value1, String value2) {
            addCriterion("source between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotBetween(String value1, String value2) {
            addCriterion("source not between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andQtyIsNull() {
            addCriterion("qty is null");
            return (Criteria) this;
        }

        public Criteria andQtyIsNotNull() {
            addCriterion("qty is not null");
            return (Criteria) this;
        }

        public Criteria andQtyEqualTo(Integer value) {
            addCriterion("qty =", value, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyNotEqualTo(Integer value) {
            addCriterion("qty <>", value, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyGreaterThan(Integer value) {
            addCriterion("qty >", value, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyGreaterThanOrEqualTo(Integer value) {
            addCriterion("qty >=", value, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyLessThan(Integer value) {
            addCriterion("qty <", value, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyLessThanOrEqualTo(Integer value) {
            addCriterion("qty <=", value, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyIn(List<Integer> values) {
            addCriterion("qty in", values, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyNotIn(List<Integer> values) {
            addCriterion("qty not in", values, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyBetween(Integer value1, Integer value2) {
            addCriterion("qty between", value1, value2, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyNotBetween(Integer value1, Integer value2) {
            addCriterion("qty not between", value1, value2, "qty");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sm_cli_area_cover_dtl
     *
     * @mbggenerated do_not_delete_during_merge Thu Aug 11 17:36:41 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sm_cli_area_cover_dtl
     *
     * @mbggenerated Thu Aug 11 17:36:41 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}