package com.huatuo.clinics.cms.db.bean;

public class TaPhaDictDrugAntibioticLevelPolity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ta_pha_dict_drug_antibiotic_level_polity.id
     *
     * @mbggenerated Thu Nov 17 10:42:07 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ta_pha_dict_drug_antibiotic_level_polity.name
     *
     * @mbggenerated Thu Nov 17 10:42:07 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ta_pha_dict_drug_antibiotic_level_polity.del_flag
     *
     * @mbggenerated Thu Nov 17 10:42:07 CST 2016
     */
    private Integer delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ta_pha_dict_drug_antibiotic_level_polity.id
     *
     * @return the value of ta_pha_dict_drug_antibiotic_level_polity.id
     *
     * @mbggenerated Thu Nov 17 10:42:07 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ta_pha_dict_drug_antibiotic_level_polity.id
     *
     * @param id the value for ta_pha_dict_drug_antibiotic_level_polity.id
     *
     * @mbggenerated Thu Nov 17 10:42:07 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ta_pha_dict_drug_antibiotic_level_polity.name
     *
     * @return the value of ta_pha_dict_drug_antibiotic_level_polity.name
     *
     * @mbggenerated Thu Nov 17 10:42:07 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ta_pha_dict_drug_antibiotic_level_polity.name
     *
     * @param name the value for ta_pha_dict_drug_antibiotic_level_polity.name
     *
     * @mbggenerated Thu Nov 17 10:42:07 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ta_pha_dict_drug_antibiotic_level_polity.del_flag
     *
     * @return the value of ta_pha_dict_drug_antibiotic_level_polity.del_flag
     *
     * @mbggenerated Thu Nov 17 10:42:07 CST 2016
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ta_pha_dict_drug_antibiotic_level_polity.del_flag
     *
     * @param delFlag the value for ta_pha_dict_drug_antibiotic_level_polity.del_flag
     *
     * @mbggenerated Thu Nov 17 10:42:07 CST 2016
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }
}